'use strict';
const addonFields=[f('included_organizations','المؤسسات المشمولة','number'),f('free_branches','الفروع الإضافية المجانية','number'),f('allow_branches','السماح بإضافة فروع','checkbox'),f('branch_monthly','سعر الفرع شهريًا — فارغ يعني غير محدد','number'),f('branch_yearly','سعر الفرع سنويًا — فارغ يعني غير محدد','number'),f('max_branches','أقصى فروع إضافية — فارغ دون حد','number'),f('verify_branches','طلب تحقق إضافي للفروع الجديدة','checkbox'),f('allow_organizations','السماح بمؤسسة أخرى','checkbox'),f('organization_monthly','المؤسسة الإضافية شهريًا','number'),f('organization_yearly','المؤسسة الإضافية سنويًا','number'),f('organization_discount','خصم المؤسسة الإضافية %','number'),f('independent_package','المؤسسة الإضافية تحتاج باقة مستقلة','checkbox'),f('max_organizations','أقصى عدد مؤسسات للحساب — يشمل الرئيسية','number')];
let addonAccount=null,addonBranch=null;
async function renderAddons(route,v){
 if(!['addons','addon-offers','accounts','account-detail','branch-detail','organization-verifications'].includes(route))return false;
 const c=$('content');let d;const valid=()=>v===version;
 if(route==='addons'){
  d=await api('addons');if(!valid())return true;c.innerHTML=note('الحد الأقصى للفروع لا يشمل المقر الرئيسي. حد المؤسسات يشمل المؤسسة الرئيسية. الأسعار غير المحددة تحتاج ضبطًا قبل تقديم طلب مدفوع.');
  append(table(d,[['الباقة',x=>pkg[x.package]],['الفروع المجانية',x=>x.free_branches],['الفروع مسموحة',x=>x.allow_branches?'نعم':'لا'],['شهري',x=>fmt(x.branch_monthly)],['سنوي',x=>fmt(x.branch_yearly)],['حد الفروع',x=>x.max_branches??'دون حد'],['مؤسسة أخرى',x=>x.allow_organizations?'نعم':'لا'],['إدارة',x=>button('تعديل الإعدادات','addon-policy',x.package)]]));c._addons=d;
  c.append(action('عروض الفروع',()=>go('addon-offers')));
 }else if(route==='addon-offers'){
  d=await api('addon-offers');if(!valid())return true;c.innerHTML=note('المقاعد تُخصص للحساب مرة واحدة عند أول طلب فرع مؤهل. تاريخ النهاية يغلق التسجيل؛ مدة الاستحقاق تبدأ عند الاستفادة. لا تجمع أعداد الفروع المجانية من عدة عروض؛ يطبق الأفضل.');
  c.append(action('إضافة عرض للفروع',()=>edit('عرض فروع',[f('name','اسم العرض'),f('packages','الباقات المشمولة','select',[['free,basic,vip','الجميع'],['basic,vip','الأساسية وVIP'],['vip','VIP'],['basic','الأساسية'],['free','المجانية']]),f('free_branches','فروع إضافية مجانية فوق الباقة','number'),f('discount_percent','خصم رسوم الفروع %','number'),f('months','مدة الاستحقاق بالأشهر','number'),f('starts_at','بداية استقبال المستفيدين','datetime-local'),f('ends_at','نهاية استقبال المستفيدين','datetime-local'),f('max_claims','أقصى مستفيدين — فارغ للجميع','number')],{packages:'vip',free_branches:1,discount_percent:0,months:3,starts_at:new Date().toISOString().slice(0,16)},x=>api('addon-offers','POST',x)),'primary'));
  append(table(d,[['العرض',x=>esc(x.name)],['الباقات',x=>esc(x.packages)],['فروع مجانية',x=>x.free_branches],['الخصم',x=>x.discount_percent+'%'],['أشهر',x=>x.months],['المستفيدون',x=>x.claimed+' / '+(x.max_claims??'دون حد')],['البداية',x=>when(x.starts_at)],['النهاية',x=>when(x.ends_at)],['الإجراء',x=>button(x.active?'إيقاف':'تشغيل','addon-offer-toggle',x.id,`data-active="${x.active?0:1}"`)]]));
 }else if(route==='accounts'){
  d=await api('accounts?page='+currentPage+'&search='+encodeURIComponent(search));if(!valid())return true;c.innerHTML='';let form=document.createElement('form');form.className='toolbar';form.innerHTML=`<input placeholder="اسم المشترك أو حسابه" value="${esc(search)}"><button>بحث</button>`;form.onsubmit=e=>{e.preventDefault();search=form.querySelector('input').value;currentPage=1;render()};c.append(form);append(table(d.items,[['المشترك',x=>button(x.name,'addon-account',x.id)],['الحساب',x=>esc(x.username)]]));pages(d);
 }else if(route==='account-detail'){
  d=await api('accounts/'+addonAccount);if(!valid())return true;c.innerHTML='';$('title').textContent='حساب المشترك: '+d.name;append(`<div class="panel"><p>إجمالي طلبات AI للحساب: ${d.ai_total}</p><p>منها غير منسوب إلى فرع: ${d.ai_unassigned}</p></div>`);
  for(let org of d.organizations){append(`<div class="panel"><h3>${button(org.name,'profile',org.id)} <span class="tag">${pkg[org.package]||'—'}</span></h3><p>${org.independent_package?'باقة مستقلة':'تتبع باقة الحساب'} · إجمالي AI: ${org.ai_total} · غير منسوب: ${org.ai_unassigned}</p><div class="toolbar">${org.branches.map(b=>button(b.name+' · '+b.status,'addon-branch',org.id,`data-branch="${esc(b.id)}"`)).join('')}</div></div>`)}
 }else if(route==='branch-detail'){
  d=await api('branches/'+addonBranch.org+'/'+encodeURIComponent(addonBranch.id));if(!valid())return true;c.innerHTML='';$('title').textContent=d.name;append(`<div class="panel"><p>المؤسسة التابعة: ${button(d.organization_name,'profile',d.organization_id)}</p><p>${esc(d.phone)} · ${esc(d.address)}</p><p>الحالة: ${esc(d.status)}</p><p>سعر الطلب المسجل: ${fmt(d.quote.amount)} · ${esc(d.period)}</p><p>انتهاء استحقاق العرض: ${when(d.quote.benefit_ends)}</p><p>AI: ${d.ai_total} · واتساب: ${fmt(d.whatsapp)} · المكالمات: ${fmt(d.calls)}</p></div>`);
  if(can('organizations.edit'))c.append(action('مراجعة الفرع وتحديث معلوماته',()=>edit('إدارة الفرع',[f('name','الاسم'),f('phone','الجوال'),f('address','العنوان'),f('status','الحالة','select',[['active','نشط'],['suspended','موقوف'],['rejected','مرفوض']]),f('reviewed','راجعت الرسوم وأي تحقق مطلوب','checkbox')],d,x=>api('branches/'+d.organization_id+'/'+d.id,'PUT',x))));
  for(let [key,label,cols]of [['employees','الموظفون',[['الاسم',x=>esc(x.name)],['الدور',x=>esc(x.role)]]],['devices','الأجهزة',[['الجهاز',x=>esc(x.device_name)],['آخر نشاط',x=>when(x.last_seen_at)]]],['ai','موظفو AI والاستهلاك',[['الموظف',x=>esc(x.employee_type)],['الطلبات',x=>x.requests]]],['vehicles','المركبات',[['الاسم',x=>esc(x.name)],['اللوحة',x=>esc(x.plate)]]],['ads','الإعلانات',[['العنوان',x=>esc(x.title)]]],['support','الدعم',[['الحالة',x=>esc(x.status)],['المشكلة',x=>esc(x.message),'wrap']]],['alerts','التنبيهات',[['الحدث',x=>esc(x.action)],['التفاصيل',x=>esc(x.summary),'wrap']]]])append('<h3>'+label+'</h3>'+table(d[key],cols));
  append(note('يظهر هنا فقط ما سُجل لهذا الفرع. السجلات القديمة التي لا تحمل فرعًا تبقى ضمن إجمالي المؤسسة دون توزيع تقديري.'));
 }else{
  d=await api('organization-verifications?page='+currentPage);if(!valid())return true;c.innerHTML=note('طلب المؤسسة الإضافية لا ينشئ فرعًا ولا يمنح الوصول إلى مؤسسة موجودة. اعتماد الملكية ينشئ كيانًا مستقلاً مرتبطًا بالحساب.');c._verifications=d.items;
  append(table(d.items,[['المشترك',x=>button(x.owner_name,'addon-account',x.account_id)],['المؤسسة المطلوبة',x=>esc(x.name)],['إثبات الملكية / المرجع',x=>esc(x.evidence),'wrap'],['الحالة',x=>esc(x.status)],['إجراء',x=>x.status==='pending'&&can('organizations.edit')?button('مراجعة التحقق','addon-review',x.id):esc(x.review_note),'wrap']]));pages(d);
 }
 return true;
}
$('content').addEventListener('click',async e=>{const b=e.target.closest('[data-act]');if(!b)return;try{
 if(b.dataset.act==='addon-policy'){const x=$('content')._addons.find(x=>x.package===b.dataset.id);edit('الفروع والإضافات · '+pkg[x.package],addonFields,x,d=>api('addons','PUT',{...d,package:x.package,revision:x.revision}))}
 if(b.dataset.act==='addon-offer-toggle'){await api('addon-offers/'+b.dataset.id,'PUT',{active:b.dataset.active==='1'});render()}
 if(b.dataset.act==='addon-account'){addonAccount=b.dataset.id;current='account-detail';render()}
 if(b.dataset.act==='addon-branch'){addonBranch={org:b.dataset.id,id:b.dataset.branch};current='branch-detail';render()}
 if(b.dataset.act==='addon-review')edit('التحقق من ملكية المؤسسة',[f('status','قرار المراجعة','select',[['approved','اعتماد'],['rejected','رفض']]),f('ownership_verified','تحققت من ملكية المؤسسة للمشترك','checkbox'),f('fees_reviewed','راجعت رسوم المؤسسة الإضافية','checkbox'),f('review_note','مرجع التحقق وسبب القرار','textarea')],{status:'approved'},d=>api('organization-verifications/'+b.dataset.id,'PUT',d));
}catch(e){flash(e.message)}});
