'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pkg={free:'المجانية',basic:'الأساسية',vip:'VIP'}, roleNames={owner:'مالك خدووم',system:'مدير النظام',manager:'مدير',support:'الدعم الفني',technician:'تقني',accounting:'المحاسبة',employee:'موظف عادي',ads:'الإعلانات',community:'مشرف المجتمع'};
const permissionNames={'organizations.view':'مشاهدة المؤسسات','organizations.edit':'تعديل المؤسسات والأجهزة',packages:'الباقات والاشتراكات',codes:'أكواد الخصم',offers:'العروض',usage:'الاستهلاك',security:'الأمن',support:'الدعم',ads:'الإعلانات',community:'المجتمع',rewards:'المكافآت',suspend:'إيقاف المؤسسات',admins:'مستخدمو الإدارة',settings:'الإعدادات',finance:'المصاريف والفواتير'};
let ownerKey='',token='',me=null,current='home',currentPage=1,filter='',search='',since='',profileId=null,version=0;
const can=p=>!p||me?.permissions.includes(p), fmt=v=>v===null||v===undefined||v===''?'غير متاح':esc(v), when=v=>{if(!v)return '—';let d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);let z=n=>String(n).padStart(2,'0');return esc(d.getFullYear()+'/'+z(d.getMonth()+1)+'/'+z(d.getDate())+' '+z(d.getHours())+':'+z(d.getMinutes()))};
async function api(path,method='GET',data){let r=await fetch(path.startsWith('/')?path:'/owner/api/v2/'+path,{method,headers:{'Content-Type':'application/json',...(ownerKey?{'X-Owner-Key':ownerKey}:{}),...(token?{'X-Admin-Session':token}:{})},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store'});let d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تنفيذ الطلب');return d}
function flash(t){$('flash').textContent=t;$('flash').hidden=false;setTimeout(()=>$('flash').hidden=true,4500)}
function action(label,fn,cls=''){let b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=async()=>{try{await fn()}catch(e){flash(e.message)}};return b}
function button(label,act,id='',extra=''){return `<button data-act="${act}" data-id="${esc(id)}" ${extra}>${esc(label)}</button>`}
function table(items,columns){return items.length?`<div class="tablewrap"><table><thead><tr>${columns.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${items.map(x=>`<tr>${columns.map(c=>`<td class="${c[2]||''}">${c[1](x)}</td>`).join('')}${current==='community-posts'&&x.user_id?`<td>${button('إعجاب','community-like',x.id)} ${button('مكافأة','community-reward',x.id)}</td>`:''}</tr>`).join('')}</tbody></table></div>`:'<div class="panel empty">لا توجد سجلات في هذا القسم.</div>'}
function pages(d){if(d.total===undefined)return;let b=document.createElement('div');b.className='toolbar';b.append(action('السابق',()=>{currentPage--;render()}),document.createTextNode(`الصفحة ${d.page} · ${d.total} سجل`),action('التالي',()=>{currentPage++;render()}));b.firstChild.disabled=d.page<=1;b.lastChild.disabled=d.page*30>=d.total;$('content').append(b)}
function tabs(options,selected,cb){let wrap=document.createElement('div');wrap.className='tabs';for(let [v,l]of options)wrap.append(action(l,()=>cb(v),selected===v?'primary':''));$('content').append(wrap)}
function note(t){return `<div class="note">${esc(t)}</div>`}
function renderOrgHealth(d){let labels={account:'الحساب',package:'الباقة',permissions:'الصلاحيات',whatsapp:'واتساب',ai:'AI',calls:'المكالمات',payment:'الدفع',server:'السيرفر'},mark=v=>v==='ok'||v==='ready'?'✅':v==='warning'||v==='pending_setup'?'⚠️':v==='not_configured'?'—':'❌',services={...(d.services||{}),calls:{...(d.services?.calls||{}),status:d.credits?.calls_status||d.services?.calls?.status,phone:d.credits?.calls_phone}};return `<div class="panel"><h3>صحة المؤسسة</h3><p>المالك: ${esc(d.owner_name||'غير محدد')} · آخر دخول: ${when(d.last_login)}</p><div class="stats">${Object.entries(services).map(([k,v])=>`<span>${labels[k]||v.label||k} ${mark(v.status)}${v.phone?' · '+esc(v.phone):''}</span>`).join('')}</div><p class="muted">آخر رسالة واتساب: ${fmt(d.services?.whatsapp?.messages)} · webhook: ${d.services?.whatsapp?.webhook?'يعمل':'غير متاح'} · طلبات AI: ${fmt(d.services?.ai?.requests)} · آخر خطأ مكالمات: ${fmt(d.credits?.calls_error)}</p></div>`}
function append(html){$('content').insertAdjacentHTML('beforeend',html)}
function communityPostCards(items){
 if(!items.length)return '<div class="panel empty">لا توجد منشورات في المجتمع.</div>';
 return '<div class="community-feed">'+items.map(x=>`<article class="community-card"><div class="community-card-head">${button(x.name,'community-user',x.user_id)}<span>${when(x.created_at)}</span></div><div class="community-body">${esc(x.body||'')}</div><div class="community-card-actions"><span class="likes">♡ ${Number(x.like_count||0)} إعجاب</span>${button('إعجاب','community-like',x.id)}${button('مكافأة صاحب المنشور','community-reward',x.id)}</div></article>`).join('')+'</div>';
}
function adminPostComposer(){
 let box=document.createElement('form');box.className='panel community-composer';box.innerHTML='<h3>منشور خدوم</h3><p class="muted">اكتب منشورًا ليظهر مباشرة في مجتمع خدوم.</p><textarea name="body" maxlength="3000" placeholder="شارك فكرة أو سؤالًا مع مؤسسات خدوم" required></textarea><div class="toolbar"><button class="primary" type="submit">نشر</button><span class="muted" data-post-status></span></div>';
 box.onsubmit=async e=>{e.preventDefault();let b=e.submitter,body=box.elements.body.value.trim();if(!body)return;b.disabled=true;try{await api('community/admin-posts','POST',{body});box.elements.body.value='';box.querySelector('[data-post-status]').textContent='تم النشر';await render()}catch(err){box.querySelector('[data-post-status]').textContent=err.message}finally{b.disabled=false}};return box;
}
function addPlatformAdButton(){
 if(ownerKey){
  $('content').append(action('إضافة إعلان منصة',()=>edit('إضافة إعلان منصة',[f('title','عنوان الإعلان'),f('message','نص الإعلان','textarea'),f('promoCode','كود الخصم (اختياري)'),f('durationDays','مدة العرض بالأيام','number')],{durationDays:30},d=>api('/owner/api/platform-ads','POST',{title:d.title,message:d.message,promoCode:d.promoCode,imageData:'',durationDays:d.durationDays})),'primary'))
 }else $('content').insertAdjacentHTML('beforeend',note('إضافة إعلان المنصة متاحة للمالك فقط.'))
}
const tree=[['الرئيسية','home',null],['الإدارة العامة',null,null,[['الباقات',null,null,[['أسعار الباقات','packages','packages'],['أكواد الخصم','codes','codes'],['عروض الباقات','offers','offers'],['أوائل المشتركين','signup','offers'],['الفروع والإضافات','addons','packages'],['طلبات الاشتراك','subscriptions','packages']]]]],['المؤسسات',null,'organizations.view',[['جميع المؤسسات','organizations','organizations.view'],['حسابات المشتركين','accounts','organizations.view'],['التحقق من الملكية','organization-verifications','organizations.view']]],['الحسابات والاستهلاك',null,'usage',[['أرصدة الخدمات','usage-credits','usage'],['الذكاء الاصطناعي','usage-ai','usage'],['واتساب','usage-whatsapp','usage'],['المكالمات','usage-calls','usage']]],['الأمن',null,'security',[['تسجيل الدخول','security-login','security'],['كلمات المرور','security-password','security'],['الأجهزة','security-devices','security'],['التنبيهات','security-alerts','security'],['سجل العمليات','security-audit','security']]],['الدعم',null,'support',[['جديدة','support-open','support'],['جاري العمل عليها','support-in_progress','support'],['محلولة','support-resolved','support'],['مغلقة','support-closed','support']]],['الإعلانات',null,'ads',[['الطلبات','ads-pending','ads'],['المجدولة','ads-scheduled','ads'],['المنشورة','ads-published','ads'],['المنتهية','ads-expired','ads'],['المرفوضة','ads-rejected','ads']]],['شات خدووم',null,'community',[['المنشورات','community-posts','community'],['التعليقات','community-comments','community'],['البلاغات','community-reports','community'],['المستخدمون','community-users','community']]],['مستخدمو الإدارة',null,'admins',[['المستخدمون','admins','admins'],['الأدوار والصلاحيات','roles','admins']]],['الإعدادات','settings',null]];
tree.splice(4,0,['المالية',null,'finance',[['المصاريف والفواتير','expenses','finance']]]);
tree.splice(5,0,['مركز الأمان','security-center','security']);
tree[8][3].push(['المحادثات المباشرة','community-chat','community']);
tree[7][3].push(['منشورات خدوم','community-admin-posts','community']);
$('communityPost').onclick=()=>edit('منشور خدوم',[f('body','نص المنشور','textarea')],{},d=>api('community/admin-posts','POST',d));
const supportStatus={'support-open':'open','support-in_progress':'in_progress','support-resolved':'resolved','support-closed':'closed'};
const adStatus={'ads-pending':'pending','ads-scheduled':'scheduled','ads-published':'published','ads-expired':'expired','ads-rejected':'rejected'};
function navNode(item){let [label,id,permission,children]=item;if(!can(permission))return null;if(children){let nodes=children.map(navNode).filter(Boolean);if(!nodes.length)return null;let e=document.createElement('details'),s=document.createElement('summary'),sub=document.createElement('div');s.textContent=label;sub.className='sub';sub.append(...nodes);e.append(s,sub);return e}let b=action(label,()=>go(id));b.dataset.route=id;return b}
function go(id){current=id;currentPage=1;filter='';search='';since='';profileId=null;render()}
async function enter(){me=await api('me');$('login').hidden=true;$('app').hidden=false;$('identity').textContent=me.name+' · '+roleNames[me.role];$('nav').replaceChildren(...tree.map(navNode).filter(Boolean));render()}
$('staffLogin').onsubmit=async e=>{e.preventDefault();try{let d=Object.fromEntries(new FormData(e.target));token=(await api('login','POST',d)).token;ownerKey='';e.target.reset();await enter()}catch(e){$('loginError').textContent=e.message}};
$('ownerLogin').onsubmit=async e=>{e.preventDefault();ownerKey=new FormData(e.target).get('key').trim();token='';try{await enter();e.target.reset()}catch(e){ownerKey='';$('loginError').textContent=e.message}};
$('logout').onclick=async()=>{try{await api('logout','POST',{})}finally{ownerKey='';token='';me=null;version++;$('app').hidden=true;$('login').hidden=false;$('content').replaceChildren()}};$('refresh').onclick=()=>render();$('cancel').onclick=()=>$('modal').close();
// Forms use DOM values and escaped labels; no server-supplied HTML is evaluated.
function edit(title,fields,values,save){$('modalTitle').textContent=title;$('formError').hidden=true;$('fields').replaceChildren();for(let f of fields){let [key,label,type,options]=f;let l=document.createElement('label');l.textContent=label;let input=document.createElement(type==='textarea'?'textarea':type==='select'?'select':'input');input.name=key;if(type==='select'){for(let [value,caption]of options){let o=document.createElement('option');o.value=value;o.textContent=caption;input.append(o)}}else if(type!=='textarea')input.type=type||'text';if(type==='checkbox'){l.className='check';input.checked=!!values[key]}else input.value=values[key]??'';if(type==='number'){input.min=0;input.step='any'}l.append(input);$('fields').append(l)}let submit=$('editor').querySelector('[type=submit]');submit.textContent=title==='منشور خدوم'?'إرسال':'حفظ';$('editor').onsubmit=async e=>{e.preventDefault();let d={};for(let [k,,type]of fields){let el=e.target.elements.namedItem(k);d[k]=type==='checkbox'?el.checked:type==='number'?(el.value===''?null:Number(el.value)):el.value}let b=e.submitter;b.disabled=true;try{await save(d);$('modal').close();flash(title==='منشور خدوم'?'تم إرسال المنشور':'تم الحفظ');await render()}catch(e){$('formError').textContent=e.message;$('formError').hidden=false}finally{b.disabled=false}};$('modal').showModal()}
const packageOptions=Object.entries(pkg), f=(key,label,type='text',options)=>[key,label,type,options];
async function render(){let v=++version;let c=$('content');c.innerHTML='<p class="muted">جارٍ تحميل البيانات…</p>';let title=[...$('nav').querySelectorAll('button')].find(b=>b.dataset.route===current)?.textContent||'ملف المؤسسة';$('title').textContent=title;$('breadcrumb').textContent='خدووم / '+title;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===current));
 try{let data;const check=()=>v===version;
 if(window.renderAddons && await renderAddons(current,v))return;
 if(current==='home'){data=await api('summary');if(!check())return;c.innerHTML='<p class="muted">ملخص المنصة · اضغط على البطاقة لعرض التفاصيل. أرقام اليوم حسب UTC.</p><div class="cards" id="cards"></div>';let cards=[['organizations','إجمالي المؤسسات','organizations'],['newToday','المشتركون الجدد اليوم','organizations'],['newMonth','المشتركون الجدد هذا الشهر','organizations'],['ai','استهلاك الذكاء الاصطناعي','usage-ai'],['whatsapp','استهلاك واتساب','usage-whatsapp'],['calls','استهلاك المكالمات','usage-calls'],['ads','الإعلانات النشطة','ads-published'],['support','طلبات الدعم المفتوحة','support-open'],['logins','محاولات الدخول اليوم','security-login'],['passwordResets','إعادة كلمات المرور','security-password'],['alerts','تنبيهات اليوم','security-alerts']];for(let [key,label,target]of cards){if(!(key in data))continue;let b=action('',()=>{go(target);if(key==='newToday'||key==='newMonth'){since=new Date().toISOString().slice(0,key==='newToday'?10:7)+(key==='newMonth'?'-01':'');render()}});b.className='metric'+(key==='support'&&Number(data[key])>0?' alert':'');b.innerHTML=esc(label)+`<strong>${fmt(data[key])}</strong>`;$('cards').append(b)}for(let x of Object.keys(pkg).map(p=>({package:p,total:(data.packages||[]).find(x=>x.package===p)?.total||0})).filter(()=>can('organizations.view'))){let b=action('',()=>{go('organizations');filter=x.package;render()});b.className='metric';b.innerHTML=esc(pkg[x.package])+`<strong>${x.total}</strong>`;$('cards').append(b)}return}
 if(current==='organizations'){data=await api(`organizations?page=${currentPage}&package=${filter}&search=${encodeURIComponent(search)}&since=${since}`);if(!check())return;c.innerHTML='';tabs([['','جميع المؤسسات'],...packageOptions],filter,x=>{filter=x;currentPage=1;render()});let form=document.createElement('form');form.className='toolbar';form.innerHTML=`<input aria-label="بحث المؤسسة" placeholder="اسم المؤسسة أو رقم التواصل" value="${esc(search)}"><button>بحث</button>`;form.onsubmit=e=>{e.preventDefault();search=form.querySelector('input').value;currentPage=1;render()};c.append(form);append(table(data.items,[['المؤسسة',x=>button(x.name,'profile',x.id)],['التواصل',x=>esc(x.phone)],['الباقة',x=>pkg[x.package]],['التسجيل',x=>when(x.created_at)],['بداية الاشتراك',x=>when(x.starts_at)],['النهاية',x=>when(x.expires_at)],['الحالة',x=>x.suspended?'موقوفة':'نشطة'],['آخر نشاط مسجل',x=>when(x.last_login)]]));pages(data);return}
 if(current==='profile'){data=await api('organizations/'+profileId);if(!check())return;c.innerHTML='';$('title').textContent=data.name;append(`<div class="panel"><h3>${esc(data.name)}</h3><p>${esc(data.activity)} · ${esc(data.phone)}</p><p>الباقة: ${pkg[data.package]} · ${data.suspended?'موقوفة':'نشطة'} · التسجيل: ${when(data.created_at)}</p><p>الاشتراك: ${when(data.starts_at)} — ${when(data.expires_at)}</p><div id="orgActions" class="toolbar"></div></div>`);if(data.account_id)$('orgActions').append(action('حساب المشترك والمؤسسات',()=>{addonAccount=data.account_id;current='account-detail';render()}));for(let branch of data.branches||[])$('orgActions').append(action(branch.name,()=>{addonBranch={org:data.id,id:branch.id};current='branch-detail';render()}));if(can('packages'))$('orgActions').append(action('تغيير الباقة',()=>edit('تغيير الباقة',[f('package','الباقة','select',packageOptions),f('durationDays','المدة بالأيام','number')],{package:data.package,durationDays:30},d=>api('/owner/api/organizations/'+profileId+'/package','PUT',d))));if(can('rewards'))$('orgActions').append(action('مكافأة يدوية',()=>edit('مكافأة المؤسسة',[f('kind','نوع المكافأة','select',[['days','إضافة أيام'],['month','شهر مجاني (30 يومًا)'],['vip','VIP لمدة محددة'],['ai','وحدات AI إضافية لليوم']]),f('amount','عدد الأيام أو الوحدات','number'),f('reason','سبب المكافأة','textarea')],{kind:'days',amount:30},d=>api('organizations/'+profileId+'/reward','POST',d))));if(can('suspend'))$('orgActions').append(action(data.suspended?'إعادة التفعيل':'إيقاف المؤسسة',()=>api('organizations/'+profileId+'/status','POST',{suspended:!data.suspended}).then(render),'danger'));if(can('organizations.edit'))$('orgActions').append(action('خروج جميع الأجهزة',()=>api('organizations/'+profileId+'/logout','POST',{}).then(render)));append('<h3>الحسابات والتواصل</h3>'+table(data.users,[['الاسم',x=>esc(x.name)],['البريد',x=>esc(x.email)],['الجوال',x=>esc(x.phone)],['الحالة',x=>x.active?'نشط':'موقوف']]));append('<h3>موظفو AI المستخدمون</h3>'+table(data.employees,[['الموظف',x=>esc(x.employee_type)],['الطلبات',x=>x.requests]]));if(can('usage'))c.append(action('عرض استهلاك المؤسسة',()=>{current='usage-ai';filter='';render()}));append('<h3>الأجهزة النشطة (حتى 100)</h3>'+table(data.devices,[['الجهاز',x=>esc(x.device_name)],['المستخدم',x=>esc(x.name)],['آخر نشاط',x=>when(x.last_seen_at)],['الإجراء',x=>can('organizations.edit')?button('تسجيل خروج','device',x.id):'—']]));append('<h3>الإعلانات (آخر 50)</h3>'+table(data.ads,[['العنوان',x=>esc(x.title)],['نهاية الإعلان',x=>when(x.expires_at)]]));append('<h3>المكافآت اليدوية</h3>'+table(data.rewards,[['النوع',x=>esc(x.kind)],['العدد',x=>x.amount],['السبب',x=>esc(x.reason)],['المسؤول',x=>esc(x.actor)],['التاريخ',x=>when(x.created_at)]]));return}
 if(current==='packages'){data=await api('packages');if(!check())return;c.innerHTML=note('الأسعار وحدود طلبات AI اليومية مرتبطة بالخادم. وحدات المكالمات وواتساب ومزايا الباقة تحتاج أن يدعمها مسار الخدمة قبل تطبيق حدودها.');append(table(data,[['الباقة',x=>pkg[x.package]],['شهري ر.س',x=>x.monthly],['سنوي ر.س',x=>x.yearly],['طلبات AI / يوم',x=>x.ai_daily],['المميزات',x=>esc(x.features),'wrap'],['إدارة',x=>button('تعديل','package',x.package)]]));c._items=data;return}
 if(current==='codes'){data=await api('codes?page='+currentPage);if(!check())return;c._items=data.items;c.innerHTML='';c.append(action('إنشاء كود خصم',()=>edit('كود خصم جديد',[f('code','الكود'),f('recipient_name','صاحب الكود'),f('discount_percent','نسبة الخصم %','number'),f('discount_amount','أو مبلغ الخصم ر.س','number'),f('starts_at','يبدأ في','datetime-local'),f('expires_at','ينتهي في','datetime-local'),f('max_uses','عدد الاستخدامات المسموحة','number'),f('eligible_packages','الباقات','select',[['basic,vip','الأساسية وVIP'],['basic','الأساسية'],['vip','VIP']])],{discount_percent:20,discount_amount:0,max_uses:100,eligible_packages:'basic,vip'},d=>api('codes','POST',d)),'primary'));append(table(data.items,[['الكود',x=>esc(x.code_prefix)],['صاحبه',x=>esc(x.recipient_name)],['الخصم',x=>x.discount_amount?x.discount_amount+' ر.س':x.discount_percent+'%'],['الاستخدام',x=>x.used_count+' / '+x.max_uses],['البداية',x=>when(x.starts_at)],['النهاية',x=>when(x.expires_at)],['إجراء',x=>button('تعديل','code-edit',x.id)+button(x.active?'إيقاف':'تشغيل','code-toggle',x.id,`data-active="${x.active?0:1}"`)]]));pages(data);return}
 if(current==='offers'){data=await api('offers');if(!check())return;c.innerHTML='';c.append(action('عروض الفروع المرتبطة بالباقات',()=>go('addon-offers')));c.append(action('إضافة عرض',()=>edit('عرض باقة',[f('label','اسم العرض'),f('package','الباقات المشمولة','select',[...packageOptions.slice(1),['basic,vip','الأساسية وVIP']]),f('offer_type','نوع العرض','select',[['price','سعر خاص'],['percent','خصم بنسبة'],['bonus','أشهر مجانية إضافية']]),f('discount_percent','نسبة الخصم %','number'),f('paid_months','الأشهر المدفوعة','number'),f('bonus_months','الأشهر المجانية','number'),f('price_sar','إجمالي سعر العرض ر.س','number'),f('starts_at','البداية','datetime-local'),f('ends_at','النهاية','datetime-local')],{package:'basic',offer_type:'price',discount_percent:0,paid_months:1,bonus_months:0,price_sar:49},d=>api('offers','POST',d)),'primary'));append(table(data,[['العرض',x=>esc(x.label)],['الباقة',x=>pkg[x.package]],['الأشهر',x=>x.paid_months+' + '+x.bonus_months],['الإجمالي',x=>x.price_sar],['البداية',x=>when(x.starts_at)],['النهاية',x=>when(x.ends_at)],['الحالة',x=>x.effective_active?'فعال':'متوقف أو خارج المدة'],['إدارة',x=>button(x.active?'إيقاف':'تشغيل','offer-toggle',x.id,`data-active="${x.active?0:1}"`)]]));return}
 if(current==='signup'){data=await api('/owner/api/signup-offer');if(!check())return;c.innerHTML=`<div class="panel"><h3>أوائل المشتركين</h3><p>المستفيدون: ${data.claimed} / ${data.max_claims} · المتبقي: ${data.remaining}</p><p>الباقة: ${pkg[data.package]} · المدة: ${data.months} أشهر</p><p>${data.enabled&&data.remaining>0?'فعال':'متوقف أو اكتملت المقاعد'}</p></div>`;c.append(action('تعديل العرض',()=>edit('أوائل المشتركين',[f('max_claims','عدد المستفيدين','number'),f('package','الباقة','select',packageOptions.slice(1)),f('months','عدد الأشهر','number'),f('enabled','فعال','checkbox')],data,d=>api('/owner/api/signup-offer','PUT',{...d,revision:data.revision}))));return}
 if(current==='usage-credits'){data=await api('credits');if(!check())return;c.innerHTML='';append(note('الأرصدة مرتبطة بالاستهلاك المسجل من AI وواتساب. المكالمات تظهر صفرًا حتى يتم تسجيل دقائق مزود الاتصال. التعديلات اليدوية تحفظ في سجل مستقل مع السبب والمنفذ والتاريخ.'));c._items=data.items;append(table(data.items,[['المؤسسة',x=>can('organizations.view')?button(x.name,'profile',x.id):esc(x.name)],['الباقة',x=>pkg[x.credits.package]],['واتساب',x=>fmt(x.credits.services.whatsapp.remaining)],['AI',x=>fmt(x.credits.services.ai.remaining)],['المكالمات',x=>fmt(x.credits.services.calls.remaining)],['الإجمالي المتبقي',x=>fmt(x.credits.total_remaining)],['استهلاك اليوم / الشهر',x=>fmt(x.credits.usage_today)+' / '+fmt(x.credits.usage_month)],['قيمة الاشتراك',x=>fmt(x.credits.subscription_value)+' ر.س'],['التكلفة الفعلية التقريبية',x=>fmt(x.credits.actual_cost)+' ر.س'],['الربح التقريبي',x=>fmt(x.credits.estimated_profit)+' ر.س'],['تنبيه',x=>Object.values(x.credits.services).some(v=>v.base>0&&v.remaining<=Math.max(1,Math.ceil(v.base*.1)))?'<span class="tag">رصيد منخفض</span>':'—'],['سجل التعديل',x=>x.credits.ledger?.length?x.credits.ledger.slice(0,2).map(v=>esc(v.service)+' '+(v.units>0?'+':'')+v.units+' — '+esc(v.reason)+' ('+esc(v.actor)+')').join('<br>'):'—'],['الإدارة',x=>button('تعديل الرصيد','credit-adjust',x.id)]]));return}
 if(current.startsWith('usage-')){let type=current.split('-')[1];data=await api(`usage?type=${type}&package=${filter}&page=${currentPage}${profileId?'&organization='+profileId:''}`);if(!check())return;c.innerHTML='';tabs([['','جميع الباقات'],...packageOptions],filter,x=>{filter=x;currentPage=1;render()});if(data.summary)append(`<div class="panel stats"><span>الكل: ${data.summary.total}</span><span>اليوم: ${data.summary.today}</span><span>الشهر: ${data.summary.month}</span></div>`);append(note(data.note||'')+table(data.items,[['المؤسسة',x=>can('organizations.view')?button(x.name,'profile',x.id):esc(x.name)],['الباقة',x=>pkg[x.package]],['الإجمالي',x=>fmt(x.total)],['استهلاك اليوم / الحد',x=>type==='ai'?`${fmt(x.today)} من ${fmt(x.daily_limit)}`:fmt(x.today)],['الشهر',x=>fmt(x.month)],['المتبقي اليوم',x=>fmt(x.remaining)],['المحادثات',x=>fmt(x.conversations)],['التكلفة',x=>fmt(x.cost)]]));pages(data);return}
 if(current.startsWith('security-')){data=await api('security?type='+current.split('-')[1]+'&page='+currentPage);if(!check())return;c.innerHTML=data.note?note(data.note):'';let columns=current==='security-audit'?[['المسؤول',x=>esc(x.actor)],['الإجراء',x=>esc(x.action)],['الهدف',x=>esc(x.target)],['الوقت',x=>when(x.created_at)]]:current==='security-devices'?[['الجهاز',x=>esc(x.device_name)],['المستخدم',x=>esc(x.name)],['موثوق',x=>x.trusted?'نعم':'لا'],['آخر نشاط',x=>when(x.last_seen_at)]]:[['المؤسسة',x=>esc(x.organization_name)],['الحدث',x=>esc(x.action)],['التفاصيل',x=>esc(x.summary),'wrap'],['الوقت',x=>when(x.created_at)]];append(table(data.items,columns));pages(data);if(data.unknownLogins?.length)append('<h3>محاولات باسم حساب غير متاح</h3>'+table(data.unknownLogins,[['الحساب',x=>esc(x.account)],['الوقت',x=>when(x.created_at)]]));if(data.adminLogins?.length)append('<h3>آخر محاولات دخول الإدارة</h3>'+table(data.adminLogins,[['الحساب',x=>esc(x.account)],['النتيجة',x=>x.success?'ناجحة':'فاشلة'],['الوقت',x=>when(x.created_at)]]));return}
 if(current==='support'||current.startsWith('support-')){let status=supportStatus[current]??filter;data=await api('support?status='+status+'&page='+currentPage);if(!check())return;c.innerHTML='';tabs([['','الكل'],['open','جديدة'],['in_progress','جاري العمل'],['resolved','محلولة'],['closed','مغلقة']],status,x=>{filter=x;currentPage=1;render()});c._items=data.items;append(table(data.items,[['المؤسسة',x=>can('organizations.view')?button(x.organization_name,'profile',x.organization_id):esc(x.organization_name)],['الباقة',x=>pkg[x.package]],['المشكلة',x=>esc(x.message),'wrap'],['الجهاز / الإصدار',x=>fmt(x.device_name)+' / '+fmt(x.app_version)],['الوقت',x=>when(x.created_at)],['الحالة',x=>esc(x.status)],['إدارة',x=>button('فتح الطلب','ticket',x.id)+button('حذف الطلب','ticket-delete',x.id)]]));pages(data);return}
 if(current==='ads'||current.startsWith('ads-')){let status=adStatus[current]??filter;data=await api('ads?status='+status+'&page='+currentPage);if(!check())return;c.innerHTML='';addPlatformAdButton();tabs([['','الكل'],['pending','طلبات جديدة / مراجعة'],['scheduled','مجدولة'],['published','منشورة'],['expired','منتهية'],['rejected','مرفوضة'],['stopped','متوقفة']],status,x=>{filter=x;current='ads';currentPage=1;render()});c._items=data.items;append(table(data.items,[['المؤسسة',x=>esc(x.organization_name)],['الإعلان',x=>(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(x.image_data||'')?`<img class="ad" alt="صورة الإعلان" src="${esc(x.image_data)}"><br>`:'')+esc(x.title)+'<br>'+esc(x.message),'wrap'],['البداية',x=>when(x.scheduled_at||x.approved_at)],['النهاية',x=>when(x.expires_at)],['الحالة',x=>esc(x.status)],['إدارة',x=>button('مراجعة','ad',x.id)+button('حذف','ad-delete',x.id)]]));pages(data);return}
 if(current==='admins'||current==='roles'){data=await api('admins');if(!check())return;c.innerHTML='';c._items=data.items;if(current==='roles'){append(table(Object.entries(data.roles),[['الدور',x=>roleNames[x[0]]],['الصلاحيات',x=>x[1].map(p=>esc(permissionNames[p])).join('، '),'wrap']]));return}c.append(action('إضافة موظف إداري',()=>adminForm({},data),'primary'));append(table(data.items,[['الاسم',x=>esc(x.name)],['اسم المستخدم',x=>esc(x.username)],['الدور',x=>roleNames[x.role]],['الحالة',x=>x.active?'نشط':'موقوف'],['إدارة',x=>button('تعديل','admin',x.id)]]));c._adminData=data;return}
 if(current==='subscriptions'){data=await api('/owner/api/subscription-requests');if(!check())return;c.innerHTML='';c._items=data;append(table(data,[['المؤسسة',x=>esc(x.organization_name)],['الباقة المطلوبة',x=>pkg[x.requested_package]],['الحالة',x=>esc(x.status)],['إجراء',x=>x.status==='pending'?button('مراجعة الاشتراك','subscription',x.id):'—']]));return}
 if(current.startsWith('community-')){let kind=current.slice(10);data=await api('community/'+kind+'?page='+currentPage);if(!check())return;c.innerHTML='';c._items=data.items;if(kind==='posts'){append('<p class="muted">المنشورات مرتبة من الأكثر إعجابًا. اضغط على اسم العضو لعرض حسابه أو على المكافأة لتكريمه.</p>'+communityPostCards(data.items));pages(data);return}if(kind==='admin-posts'){c.append(adminPostComposer());append(table(data.items,[['المنشور',x=>esc(x.body),'wrap'],['الكاتب',x=>esc(x.name)],['الوقت',x=>when(x.created_at)],['الحالة',x=>esc(x.hidden?'مخفي':'ظاهر')],['إجراء',x=>button(x.hidden?'إظهار':'إخفاء','community-hide',x.id,`data-kind="${kind}" data-hidden="${x.hidden?0:1}"`)]]));return}append(table(data.items,[['المستخدم',x=>button(x.name,'community-user',kind==='users'?x.id:x.user_id)],['النص / البلاغ',x=>esc(x.body||x.reason||x.organization_name),'wrap'],['الوقت',x=>when(x.created_at||x.last_post)],['الحالة',x=>esc(x.status||(x.hidden?'مخفي':'ظاهر'))],['إجراء',x=>kind==='reports'?button('معالجة البلاغ','community-report',x.id):kind==='users'?'—':button(x.hidden?'إظهار':'إخفاء','community-hide',x.id,`data-kind="${kind}" data-hidden="${x.hidden?0:1}"`)]]));pages(data);return}
 if(current==='expenses'){data=await api('expenses');if(!check())return;c.innerHTML='';append('<div class="panel"><h3>المصاريف والفواتير</h3><p class="muted">قسم مالي داخلي لخدووم. الدفع التلقائي غير مفعّل حاليًا.</p><div class="stats"><span>مصاريف الشهر: <b>'+fmt(data.monthExpenses)+' ر.س</b></span><span>المدفوع: <b>'+fmt(data.paid)+' ر.س</b></span><span>المتبقي: <b>'+fmt(data.remaining)+' ر.س</b></span><span>المتأخر: <b>'+fmt(data.overdue)+' ر.س</b></span><span>القادم: <b>'+fmt(data.upcoming)+' ر.س</b></span><span>دخل الاشتراكات: <b>'+fmt(data.subscriptionIncome)+' ر.س</b></span><span>الصافي: <b>'+fmt(data.net)+' ر.س</b></span></div></div>');c.append(action('إضافة فاتورة / مصروف',()=>edit('إضافة مصروف',[f('provider','اسم المزود'),f('service','نوع الخدمة','select',[['whatsapp','واتساب'],['calls','المكالمات'],['ai','الذكاء الاصطناعي AI'],['server','السيرفرات'],['database','قاعدة البيانات'],['payment','بوابة الدفع'],['ads','الإعلانات'],['development','التطوير'],['freelancers','الفريلانسرز'],['salaries','الرواتب'],['other','أخرى']]),f('invoice_number','رقم الفاتورة'),f('subtotal','القيمة قبل الضريبة','number'),f('tax','الضريبة','number'),f('issued_at','تاريخ الإصدار'),f('due_at','تاريخ الاستحقاق'),f('status','الحالة','select',[['unpaid','غير مدفوعة'],['paid','مدفوعة']]),f('payment_method','طريقة الدفع'),f('notes','ملاحظات','textarea'),f('recurring','مصروف متكرر','checkbox')],{service:'other',subtotal:0,tax:0,status:'unpaid',recurring:false},d=>api('expenses','POST',d)),'primary'));c._items=data.items;append(table(data.items,[['المزود',x=>esc(x.provider)],['الخدمة',x=>esc(x.service)],['الإجمالي',x=>fmt(x.total)+' ر.س'],['الاستحقاق',x=>when(x.due_at)],['الحالة',x=>x.status==='paid'?'مدفوعة':x.status==='overdue'?'متأخرة':'غير مدفوعة'],['الإجراء',x=>(x.status==='paid'?'—':button('تسجيل الدفع','expense-pay',x.id))+' '+button('حذف','expense-delete',x.id)]]));return}
 if(current==='settings'){data=await api('settings');if(!check())return;c.innerHTML=`<div class="panel"><p>قاعدة البيانات: ${esc(data.database)}</p><p>مدة جلسة الموظف الإداري: ${data.sessionHours} ساعات</p><p>عدد النتائج في الصفحة: ${data.pageSize}</p></div>`+note(data.note);return}
 }catch(e){if(v===version)c.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function adminForm(x,d){let fields=[f('name','اسم الموظف'),f('username','اسم المستخدم بالإنجليزية'),f('password',x.id?'كلمة مرور جديدة (اتركها للإبقاء)':'كلمة المرور — 12 حرفًا على الأقل','password'),f('role','الدور الجاهز','select',Object.entries(roleNames)),f('active','نشط','checkbox'),...d.permissions.map(p=>f('perm_'+p,permissionNames[p],'checkbox'))];let permissions=x.permissions?JSON.parse(x.permissions):d.roles.support;let values={role:'support',active:true,...x,...Object.fromEntries(d.permissions.map(p=>['perm_'+p,permissions.includes(p)]))};edit(x.id?'تعديل موظف إداري':'موظف إداري جديد',fields,values,v=>{let permissions=d.permissions.filter(p=>v['perm_'+p]);return api('admins'+(x.id?'/'+x.id:''),x.id?'PUT':'POST',{name:v.name,username:v.username,password:v.password,role:v.role,active:v.active,permissions})});$('editor').elements.role.onchange=e=>{for(let p of d.permissions)$('editor').elements.namedItem('perm_'+p).checked=d.roles[e.target.value].includes(p)}}
$('content').onclick=async e=>{let b=e.target.closest('[data-act]');if(!b)return;let id=b.dataset.id,act=b.dataset.act,items=$('content')._items||[];let x=items.find(x=>String(x.id)===id);try{
 if(act==='profile'){profileId=Number(id);current='profile';currentPage=1;await render()}
 if(act==='credit-adjust'){edit('تعديل رصيد خدمات '+x.name,[f('service','الخدمة','select',[['whatsapp','واتساب'],['ai','الذكاء الاصطناعي'],['calls','المكالمات']]),f('units','الوحدات (+ زيادة / - تخفيض)','number'),f('reason','سبب التعديل','textarea')],{service:'whatsapp',units:1,reason:'تعويض أو تعديل يدوي'},d=>api('credits/'+id,'POST',d));}
 if(act==='device'){await api('organizations/'+profileId+'/logout','POST',{device:id});await render()}
 if(act==='expense-pay'){if(confirm('تأكيد تسجيل دفع هذه الفاتورة؟')){await api('expenses/'+id,'PUT',{status:'paid',payment_method:'مسجل من لوحة أمن خدووم',payment_reference:'',notes:x.notes||''});await render()}}
 if(act==='expense-delete'){if(confirm('حذف الفاتورة؟ سيتم حفظ سجل العملية فقط.')){await api('expenses/'+id,'DELETE');await render()}}
 if(act==='package'){x=items.find(x=>x.package===id);edit('إعدادات '+pkg[id],[f('monthly','شهري ر.س','number'),f('yearly','سنوي ر.س','number'),f('ai_daily','طلبات AI في اليوم','number'),f('ai_employees','موظفو AI — تعريف الباقة','number'),f('whatsapp_units','وحدات واتساب — تعريف الباقة','number'),f('calls_units','دقائق المكالمات — تعريف الباقة','number'),f('ads_units','الإعلانات — تعريف الباقة','number'),f('features','المميزات','textarea')],x,d=>api('packages','PUT',{...d,package:id}))}
 if(act==='code-edit')edit('تعديل الكود مع حفظ عدد استخداماته',[f('recipient_name','صاحب الكود'),f('discount_percent','النسبة %','number'),f('discount_amount','أو مبلغ الخصم','number'),f('max_uses','الاستخدامات المسموحة','number'),f('eligible_packages','الباقات','select',[['basic,vip','الأساسية وVIP'],['basic','الأساسية'],['vip','VIP']]),f('starts_at','البداية','datetime-local'),f('expires_at','النهاية','datetime-local')],{...x,starts_at:x.starts_at?.slice(0,16),expires_at:x.expires_at?.slice(0,16)},d=>api('codes/'+id,'PUT',d));
 if(act==='code-toggle'||act==='offer-toggle'){await api((act==='code-toggle'?'codes/':'offers/')+id,'PUT',{active:b.dataset.active==='1'});render()}
 if(act==='ticket'){edit('طلب الدعم #'+id,[f('status','الحالة','select',[['open','جديدة'],['in_progress','جاري العمل'],['resolved','محلولة'],['closed','مغلقة']]),f('owner_reply','الرد للمشترك','textarea'),f('note','ملاحظة داخلية جديدة','textarea')],x,d=>api('support/'+id,'PUT',d));if(x.organization_id){$('fields').append(action('إرسال للموظف التقني AI',async()=>{let r=await api('support/'+id+'/technical-followup','POST',{});flash(r.message);x.notes.unshift({actor:'لوحة أمن خدووم',note:r.message,created_at:new Date().toISOString()})},'primary'));$('fields').append(action('فتح ملف المؤسسة والصيانة',()=>{$('modal').close();profileId=Number(x.organization_id);current='profile';render()}))}if(x.notes.length){let p=document.createElement('p');p.className='muted';p.textContent=x.notes.map(n=>n.actor+': '+n.note).join('\n');$('fields').append(p)}}
 if(act==='ticket-delete'){if(confirm('حذف طلب الدعم نهائيًا؟')){await api('support/'+id,'DELETE');render()}}
 if(act==='ad-delete'){if(confirm('حذف الإعلان من العرض؟ سيبقى سجل الإجراء محفوظًا.')){await api('ads/'+id,'DELETE');render()}}
 if(act==='ad')edit('مراجعة الإعلان',[f('status','الحالة','select',[['pending','تحت المراجعة'],['published','موافقة ونشر'],['scheduled','جدولة'],['rejected','رفض'],['stopped','إيقاف']]),f('scheduled_at','موعد البداية','datetime-local'),f('expires_at','موعد النهاية','datetime-local'),f('review_note','ملاحظة المراجعة','textarea')],{...x,scheduled_at:x.scheduled_at?.slice(0,16),expires_at:x.expires_at?.slice(0,16)},d=>api('ads/'+id,'PUT',d));
 if(act==='community-like'){await api('community/likes/'+id,'POST',{});flash('تم تسجيل الإعجاب');render()}
 if(act==='community-reward')edit('مكافأة صاحب المنشور',[f('kind','نوع المكافأة','select',[['days','أيام إضافية'],['ai','رصيد AI إضافي']]),f('amount','العدد','number'),f('reason','السبب','textarea')],{kind:'days',amount:30,reason:'منشور مميز في مجتمع خدوم'},d=>api('community/rewards/'+id,'POST',d));
 if(act==='community-hide'){await api('community/'+b.dataset.kind+'/'+id,'PUT',{hidden:b.dataset.hidden==='1'});render()}
 if(act==='community-report')edit('معالجة البلاغ',[f('status','الحالة','select',[['open','مفتوح'],['closed','مغلق']]),f('note','ملاحظة الإدارة','textarea')],x,d=>api('community/reports/'+id,'PUT',d));
 if(act==='community-user'&&current==='community-chat'){let chat=await api('community/chat/'+id),text=(chat.items||[]).map(m=>(m.sender==='admin'?'الإدارة':'العضو')+': '+m.body).join('\n\n');edit('محادثة مباشرة مع '+(x?.name||'العضو'),[f('body','اكتب ردك','textarea')],{},d=>api('community/chat/'+id,'POST',d));let log=document.createElement('pre');log.textContent=text||'لا توجد رسائل بعد';log.style.whiteSpace='pre-wrap';log.style.maxHeight='260px';log.style.overflow='auto';$('fields').prepend(log)}
 if(act==='community-user'){let user=await api('community/users/'+id);edit(user.name,[f('organization','المؤسسة'),f('phone','الجوال'),f('email','البريد')],{organization:user.organization_name,phone:user.phone,email:user.email},async()=>{});let submit=$('editor').querySelector('[type=submit]');submit.hidden=true;$('modal').addEventListener('close',()=>submit.hidden=false,{once:true});if(can('rewards'))$('fields').append(action('إعطاء مكافأة يدوية',()=>{ $('modal').close();edit('مكافأة '+user.name,[f('kind','النوع','select',[['days','أيام مجانية'],['vip','VIP'],['ai','وحدات AI لليوم']]),f('amount','العدد','number'),f('reason','السبب','textarea')],{amount:30,kind:'days'},d=>api('organizations/'+user.organization_id+'/reward','POST',d))}));}
 if(act==='admin')adminForm(x,$('content')._adminData);
 if(act==='subscription')edit('مراجعة الاشتراك',[f('status','القرار','select',[['approved','موافقة'],['rejected','رفض']]),f('package','الباقة','select',packageOptions),f('durationDays','مدة الأيام','number')],{status:'approved',package:x.requested_package,durationDays:30},d=>api('/owner/api/subscription-requests/'+id,'PUT',{action:d.status==='approved'?'approve':'reject',selectedPackage:d.package,durationDays:d.durationDays}));
}catch(e){flash(e.message)}};
const khdoomBaseRender=render;render=async function(){await khdoomBaseRender();if(current==='profile'&&!$('orgHealth')){try{let d=await api('organizations/'+profileId);append('<div id="orgHealth">'+renderOrgHealth(d)+'</div>')}catch(_){}}};
const khdoomHealthRender=render;render=async function(){await khdoomHealthRender();if(current==='service-health'){let d=await api('service-health');if(!check())return;let html='<div class="panel"><h3>مركز الأعطال وصحة الخدمات</h3><p class="muted">آخر فحص: '+when(d.checkedAt)+'</p></div>'+table(d.services,[['الخدمة',x=>esc(x.label)],['الحالة',x=>x.status==='ready'?'✅ جاهزة':x.status==='warning'?'⚠️ تحتاج متابعة':x.status==='not_configured'?'— غير مهيأة':'❌ غير مربوطة'],['المؤسسات المتأثرة',x=>fmt(x.affected)],['آخر خطأ',x=>esc(x.lastError||'لا يوجد'),'wrap'],['إجراء',x=>'<button onclick="khdoomHealthCheck(\''+esc(x.service)+'\')">فحص الخدمة</button>']]);$('content').innerHTML=html}};
async function khdoomHealthCheck(service){let r=await fetch('/owner/api/v2/service-health/check',{method:'POST',headers:hdr(),body:JSON.stringify({service})}),d=await r.json();alert(r.ok?(d.message||'تم طلب الفحص'):(d.error||'تعذر فحص الخدمة'));if(r.ok)render()}
const khdoomLowBalanceRender=render;render=async function(){await khdoomLowBalanceRender();if(current==='home'&&!$('lowBalanceSummary')){try{let d=await api('summary'),box=document.createElement('div');box.id='lowBalanceSummary';box.className='panel';box.innerHTML='<h3>تنبيهات الرصيد</h3><p class="'+(Number(d.lowBalanceOrganizations)>0?'danger':'ok')+'">مؤسسات برصيد منخفض: <b>'+fmt(d.lowBalanceOrganizations)+'</b></p>';$('content').append(box)}catch(_){}}};
const khdoomOrgCreditsRender=render;render=async function(){await khdoomOrgCreditsRender();if(current==='profile'&&!$('orgCredits')){try{let d=await api('organizations/'+profileId),c=d.credits||{},box=document.createElement('div');box.id='orgCredits';box.className='panel';let serviceRows=Object.values(c.services||{}).map(v=>'<span>'+esc(v.label)+': المتبقي <b>'+fmt(v.remaining)+'</b> · اليوم '+fmt(v.used_today)+' · الشهر '+fmt(v.used_month)+' · التكلفة '+fmt(v.cost)+' ر.س</span>').join('');box.innerHTML='<h3>أرصدة واستهلاك المؤسسة</h3><div class="stats">'+serviceRows+'</div><p>إجمالي الوحدات المتبقية: <b>'+fmt(c.total_remaining)+'</b> · قيمة الاشتراك: <b>'+fmt(c.subscription_value)+' ر.س</b> · التكلفة الفعلية: <b>'+fmt(c.actual_cost)+' ر.س</b> · الربح التقريبي: <b>'+fmt(c.estimated_profit)+' ر.س</b></p>';$('content').append(box)}catch(_){}}};
const khdoomTechnicalAiRender=render;render=async function(){await khdoomTechnicalAiRender();if(current==='technical-ai'){let d=await api('technical-ai');if(!check())return;$('content').innerHTML='<div class="panel"><h3>الموظف التقني AI</h3><p class="muted">تشخيص واقتراحات آمنة فقط؛ لا تعديل مباشر على الإنتاج ولا حذف للبيانات.</p><button onclick="khdoomDiagnose(\'login\')">تشخيص تسجيل الدخول</button> <button onclick="khdoomDiagnose(\'whatsapp\')">تشخيص واتساب</button> <button onclick="khdoomDiagnose(\'ai\')">تشخيص AI</button> <button onclick="khdoomDiagnose(\'calls\')">تشخيص المكالمات</button></div>'+table(d.items,[['الخدمة',x=>esc(x.service)],['المشكلة',x=>esc(x.problem),'wrap'],['السبب المتوقع',x=>esc(x.root_cause),'wrap'],['الإصلاح المقترح',x=>esc(x.proposal),'wrap'],['الاختبار',x=>esc(x.test_status)],['النشر',x=>esc(x.deployment_status)],['إجراءات',x=>x.test_status==='not_tested'?'<button onclick="khdoomTechnicalAction('+x.id+',\'test\')">اختبار</button>':x.deployment_status==='proposed'?'<button onclick="khdoomTechnicalAction('+x.id+',\'approve\')">موافقة</button>':'—']])}};
async function khdoomDiagnose(service){let r=await fetch('/owner/api/v2/technical-ai/diagnose',{method:'POST',headers:hdr(),body:JSON.stringify({service})}),d=await r.json();alert(r.ok?'تم إنشاء تشخيص آمن للمراجعة':(d.error||'تعذر التشخيص'));if(r.ok)render()}
async function khdoomTechnicalAction(id,action){if(action==='approve'&&!confirm('تأكيد الموافقة؟ لن يتم نشر كود تلقائيًا.'))return;let r=await fetch('/owner/api/v2/technical-ai/'+id+'/'+action,{method:'POST',headers:hdr()}),d=await r.json();alert(r.ok?(d.message||'تم التنفيذ'):(d.error||'تعذر التنفيذ'));if(r.ok)render()}
const khdoomFutureModulesRender=render;render=async function(){await khdoomFutureModulesRender();if(current==='home'&&!$('futureModulesLink')){let b=action('التكاملات والخدمات المستقبلية',()=>go('integrations'));b.id='futureModulesLink';b.className='primary';$('content').append(b)}if(current==='integrations'){let d=await api('integrations');$('content').innerHTML='<div class="panel"><h3>التكاملات والخدمات المستقبلية</h3><p class="muted">كل وحدة مستقلة عن الأخرى، ولا يتم تفعيلها قبل توفر مزود رسمي وإعداد خادم وصلاحيات واضحة.</p></div>'+table(d.items,[['الوحدة',x=>esc(x.name)],['التصنيف',x=>esc(x.category)],['الحالة',x=>x.status==='active'?'✅ مفعلة':'قريبًا'],['الصلاحية المطلوبة',x=>esc(x.required_permission)],['الإعداد',x=>x.provider_configured?'مهيأ':'غير مهيأ'],['ملاحظات',x=>esc(x.notes),'wrap']])}};
const khdoomHealthNav=render;render=async function(){await khdoomHealthNav();if(current==='home'&&!$('healthLink')){let b=action('فتح مركز الأعطال',()=>go('service-health'));b.id='healthLink';b.className='primary';$('content').prepend(b)}};
const khdoomControlCenterRender=render;render=async function(){await khdoomBaseRender();if(current==='profile'&&!$('orgHealth')){try{let d=await api('organizations/'+profileId);append('<div id="orgHealth">'+renderOrgHealth(d)+'</div>')}catch(_){}}if(current==='home'&&!$('controlCenterSummary')){try{let d=await api('summary');let box=document.createElement('div');box.id='controlCenterSummary';box.className='panel';box.innerHTML='<h3>مركز التحكم والتشخيص</h3><div class="stats"><span>المشتركون النشطون <b>'+fmt(d.activeSubscribers)+'</b></span><span>اشتراكات تنتهي خلال 14 يومًا <b>'+fmt(d.expiringSubscriptions)+'</b></span><span>مكالمات فاشلة <b>'+fmt(d.callFailures)+'</b></span></div>';document.querySelector('#content')?.prepend(box)}catch(_){}}};
const khdoomFinalRender=render;render=async function(){await khdoomFinalRender();if(current==='home'&&!$('technicalAiLink')){let b=action('فتح الموظف التقني AI',()=>go('technical-ai'));b.id='technicalAiLink';b.className='primary';$('content').prepend(b)}if(current==='technical-ai'){let d=await api('technical-ai');$('content').innerHTML='<div class="panel"><h3>الموظف التقني AI</h3><p class="muted">تشخيص واقتراحات آمنة فقط؛ لا تعديل مباشر على الإنتاج ولا حذف للبيانات.</p><button onclick="khdoomDiagnose(\'whatsapp\')">تشخيص واتساب</button> <button onclick="khdoomDiagnose(\'ai\')">تشخيص AI</button> <button onclick="khdoomDiagnose(\'calls\')">تشخيص المكالمات</button></div>'+table(d.items,[['الخدمة',x=>esc(x.service)],['المشكلة',x=>esc(x.problem),'wrap'],['السبب المتوقع',x=>esc(x.root_cause),'wrap'],['الإصلاح المقترح',x=>esc(x.proposal),'wrap'],['الاختبار',x=>esc(x.test_status)],['النشر',x=>esc(x.deployment_status)],['إجراءات',x=>x.test_status==='not_tested'?'<button onclick="khdoomTechnicalAction('+x.id+',\'test\')">اختبار</button>':x.deployment_status==='proposed'?'<button onclick="khdoomTechnicalAction('+x.id+',\'approve\')">موافقة</button>':'—']])}};
const khdoomFutureFinal=render;render=async function(){await khdoomFutureFinal();if(current==='home'&&!$('futureModulesLink')){let b=action('التكاملات والخدمات المستقبلية',()=>go('integrations'));b.id='futureModulesLink';b.className='primary';$('content').append(b)}if(current==='integrations'){let d=await api('integrations');$('content').innerHTML='<div class="panel"><h3>التكاملات والخدمات المستقبلية</h3><p class="muted">كل وحدة مستقلة عن الأخرى، ولا يتم تفعيلها قبل توفر مزود رسمي وإعداد خادم وصلاحيات واضحة.</p></div>'+table(d.items,[['الوحدة',x=>esc(x.name)],['التصنيف',x=>esc(x.category)],['الحالة',x=>x.status==='active'?'✅ مفعلة':'قريبًا'],['الصلاحية المطلوبة',x=>esc(x.required_permission)],['الإعداد',x=>x.provider_configured?'مهيأ':'غير مهيأ'],['ملاحظات',x=>esc(x.notes),'wrap']])}};
const khdoomTechnicalMonitorRender=render;render=async function(){await khdoomTechnicalMonitorRender();if(current==='technical-ai'&&!$('technicalState')){try{let d=await api('technical-ai'),s=d.state||{},label={online:'شغال ✅',working:'مشغول 🔵',offline:'غير متصل 🔴',not_configured:'غير مهيأ ⚪'}[s.status]||'غير متصل 🔴';append('<div id="technicalState" class="panel"><h3>حالة الموظف التقني AI</h3><p><b>'+label+'</b> · آخر Heartbeat: '+when(s.lastHeartbeat)+'</p><p>آخر فحص: '+esc(s.lastCheck||'—')+' · آخر مهمة: '+esc(s.lastTask||'—')+'</p><p>آخر خطأ: '+esc(s.lastError||'لا يوجد')+' · آخر نجاح: '+esc(s.lastSuccess||'—')+'</p></div><h3>سجل مهام الموظف التقني AI</h3>'+table(d.tasks||[],[['المؤسسة',x=>esc(x.organization_name||'عامة')],['المستخدم',x=>esc(x.user_name||'—')],['الخدمة',x=>esc(x.service)],['المشكلة',x=>esc(x.problem),'wrap'],['الخطورة',x=>esc(x.severity)],['الحالة',x=>esc(x.status)],['البداية',x=>when(x.started_at)],['النتيجة',x=>esc(x.result||'—'),'wrap']]))}catch(_){}}};
const khdoomSecurityCenterRender=render;render=async function(){await khdoomSecurityCenterRender();if(current==='security-center'&&!$('securityCenter')){try{let d=await api('security-center');append('<div id="securityCenter" class="panel"><h3>مركز الأمان</h3><div class="stats"><span>جدار التطبيق: <b>يعمل</b></span><span>حد الطلبات: <b>'+d.rateLimit.maxRequestsPerWindow+' / دقيقة</b></span><span>HTTPS: <b>'+esc(d.https)+'</b></span></div><p class="muted">الأسرار: '+esc(d.secrets)+'</p><p class="muted">النسخ الاحتياطية: '+esc(d.backups)+'</p></div><h3>محاولات الدخول الفاشلة</h3>'+table(d.failedLogins||[],[['الحساب',x=>esc(x.account)],['IP',x=>esc(x.ip)],['الوقت',x=>when(x.created_at)]] )+'<h3>الأجهزة المحظورة</h3>'+table(d.blockedDevices||[],[['المؤسسة',x=>fmt(x.organization_id)],['الجهاز',x=>esc(x.device_name)],['وقت الحظر',x=>when(x.blocked_at)]]))}catch(_){}}};
const khdoomLoginDiagnosticsRender=render;render=async function(){await khdoomLoginDiagnosticsRender();if(current==='technical-ai'&&!$('loginDiagnostics')){try{let d=await api('technical-ai');let yes=v=>Number(v)?'✅':'❌';append('<div id="loginDiagnostics" class="panel"><h3>تشخيص أخطاء تسجيل الدخول</h3>'+(d.loginAlert?'<p class="error">عطل عام محتمل في تسجيل الدخول: تكررت الأخطاء من أكثر من مستخدم أو جهاز خلال آخر 10 دقائق.</p>':'<p class="muted">يتم التسجيل والتشخيص تلقائيًا دون حفظ كلمات المرور أو الرموز السرية.</p>')+table(d.loginFailures||[],[['المؤسسة',x=>esc(x.organization_name||'غير معروفة')],['المستخدم',x=>esc(x.user_name||x.username)],['الجهاز',x=>esc(x.device_name||'—')],['الإصدار',x=>esc(x.app_version||'غير متاح')],['الكود',x=>fmt(x.error_code)],['المستخدم موجود',x=>yes(x.user_exists)],['الحساب فعال',x=>yes(x.account_active)],['قاعدة البيانات',x=>esc(x.database_status||'—')],['Login API',x=>fmt(x.error_code)],['السبب المتوقع',x=>esc(({password_verification_failed:'فشل التحقق من كلمة المرور',user_not_found:'المستخدم غير موجود أو لم تتم مزامنته',account_inactive:'الحساب موقوف',organization_suspended:'المؤسسة موقوفة',device_blocked:'الجهاز محظور'}[x.reason]||x.reason))],['الحالة',x=>'تم التشخيص ✅'],['الوقت',x=>when(x.created_at)]]))}catch(_){}}};
async function khdoomScanOrg(id){try{let d=await api('technical-ai/organization/'+id+'/scan','POST',{}),box=document.createElement('div');box.className='panel';box.innerHTML='<h3>تقرير الفحص الشامل</h3>'+table(d.checks||[],[['الفحص',x=>esc(x.label)],['الحالة',x=>x.status==='ok'?'✅ سليم':'⚠️ يحتاج متابعة'],['التفاصيل',x=>esc(x.details),'wrap']]);$('content').append(box)}catch(e){flash(e.message)}}
const khdoomTechnicalToolsRender=render;render=async function(){await khdoomTechnicalToolsRender();if(current==='technical-ai'&&!$('technicalAsk')){let box=document.createElement('form');box.id='technicalAsk';box.className='panel';box.innerHTML='<h3>اسأل الموظف التقني</h3><p class="muted">اكتب المشكلة بلغتك العادية، وسيحدد المؤسسة والخدمة ويجمع التشخيص.</p><textarea name="question" required placeholder="مثال: مؤسسة فلان لا تستطيع تسجيل الدخول، افحص المشكلة"></textarea><div class="toolbar"><button class="primary">بدء التشخيص</button><span class="muted" data-result></span></div>';box.onsubmit=async e=>{e.preventDefault();let button=e.submitter;button.disabled=true;try{let d=await api('technical-ai/ask','POST',{question:box.elements.question.value});box.querySelector('[data-result]').textContent=(d.diagnosis||'تم التشخيص')+' — الإجراء: '+(d.proposal||'مراجعة التقرير');await render()}catch(err){box.querySelector('[data-result]').textContent=err.message}finally{button.disabled=false}};$('content').prepend(box)}if(current==='profile'&&$('orgActions')&&!$('fullScanButton')){let b=action('فحص شامل',()=>khdoomScanOrg(profileId),'primary');b.id='fullScanButton';$('orgActions').append(b)}};
document.addEventListener('submit',async e=>{if(e.target.id!=='technicalAsk')return;e.preventDefault();e.stopImmediatePropagation();let form=e.target,button=e.submitter,result=form.querySelector('[data-result]'),question=form.elements.question.value.trim();if(!question)return;button.disabled=true;result.textContent='جاري التشخيص…';result.style.color='#2563eb';let old=document.getElementById('technicalAskResult');if(old)old.remove();try{let d=await api('technical-ai/ask','POST',{question}),box=document.createElement('div');box.id='technicalAskResult';box.className='panel';box.innerHTML='<h3>نتيجة التشخيص</h3><p><b>الحالة:</b> تم التشخيص ✅ · رقم المهمة: '+fmt(d.taskId)+'</p><p><b>المؤسسة:</b> '+esc(d.organization?.name||'لم يتم تحديدها')+' · <b>الخدمة:</b> '+esc(d.service||'—')+'</p><p><b>التشخيص:</b> '+esc(d.diagnosis||'—')+'</p><p><b>الإجراء المقترح:</b> '+esc(d.proposal||'—')+'</p><p><b>الموافقة:</b> '+(d.requiresApproval?'مطلوبة قبل الإجراء الحساس':'لا يوجد إجراء حساس')+'</p>';form.after(box);result.textContent='تم حفظ المهمة في سجل الموظف التقني AI';result.style.color='#15803d';}catch(err){result.textContent=err.message;result.style.color='#b91c1c';}finally{button.disabled=false;}},true);
const khdoomMonitorBadgeRender=render;render=async function(){await khdoomMonitorBadgeRender();if(current==='technical-ai'&&!$('monitorBadge')){try{let d=await api('technical-ai'),s=d.state||{},online=s.status==='online'||s.status==='working';append('<div id="monitorBadge" class="panel" style="border-right:5px solid '+(d.monitoring?'#16a34a':'#f59e0b')+'"><h3>مراقبة خدووم</h3><p><b style="color:'+(d.monitoring?'#15803d':'#b45309')+'">'+(d.monitoring?'المراقبة التلقائية تعمل ✅':'المراقبة غير مفعلة')+'</b> · الموظف التقني: '+(online?'يتابع الآن 🔵':s.status==='not_configured'?'غير مهيأ ⚪':'غير متصل 🔴')+'</p><p class="muted">آخر فحص: '+when(s.lastCheck)+' · آخر مهمة: '+esc(s.lastTask||'لا توجد مهام حالية')+'</p>'+((d.tasks||[]).length?'':'<p class="muted">لا توجد بيانات تشخيص بعد؛ ستظهر هنا تلقائيًا عند اكتشاف مشكلة أو تنفيذ فحص.</p>')+'</div>')}catch(_){}}};
const khdoomReadinessRender=render;render=async function(){await khdoomReadinessRender();if(current==='home'&&!$('readinessLink')){let b=action('فحص الجاهزية قبل الإطلاق',()=>go('readiness'),'primary');b.id='readinessLink';$('content').prepend(b)}if(current==='readiness'){let d=await api('readiness'),r=d.latestRun,s=d.results||[];if(!r){$('content').innerHTML='<div class="panel"><h3>فحص الجاهزية قبل الإطلاق</h3><p class="muted">لم يتم تشغيل الفحص بعد. الوضع آمن: لا دفع حقيقي ولا حذف أو تعديل لبيانات المشتركين.</p><button class="primary" id="runReadiness">تشغيل فحص شامل</button></div>';$("runReadiness").onclick=async()=>{await api('readiness/run','POST',{});await render()};return}let mark=x=>x==='ready'?'✅ جاهز':x==='review'?'🟡 يحتاج مراجعة':x==='warning'?'⚠️ يوجد تحذير':'❌ غير جاهز';$('content').innerHTML='<div class="panel"><h2>فحص الجاهزية قبل الإطلاق</h2><h1>جاهزية خدووم للإطلاق: '+r.score+'%</h1><p>✅ '+r.ready_count+' أنظمة جاهزة · ⚠️ '+r.review_count+' تحتاج مراجعة · ❌ '+r.failed_count+' غير جاهزة</p><p class="muted">آخر فحص: '+when(r.finished_at)+' · الوضع: Safe/Test فقط</p><button class="primary" id="runReadiness">إعادة تشغيل فحص شامل</button></div>'+table(s,[['الخدمة',x=>esc(x.label)],['الحالة',x=>mark(x.status)],['نتيجة الفحص',x=>esc(x.result),'wrap'],['الخطأ',x=>esc(x.error||'لا يوجد'),'wrap'],['الإجراء المقترح',x=>esc(x.proposal||'لا يوجد'),'wrap'],['آخر فحص',x=>when(x.checked_at)],['الإجراء',x=>'<button data-readiness-ref="'+esc(x.service_key)+'">إعادة الفحص</button>']]);$("runReadiness").onclick=async()=>{await api('readiness/run','POST',{});await render()};document.querySelectorAll('[data-readiness-ref]').forEach(b=>b.onclick=async()=>{await api('readiness/run','POST',{});await render()})}};
