'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pkg={free:'المجانية',basic:'الأساسية',vip:'VIP'}, roleNames={owner:'المالك',system:'مدير النظام',support:'الدعم الفني',accounting:'المحاسبة',ads:'الإعلانات',community:'مشرف المجتمع'};
const permissionNames={'organizations.view':'مشاهدة المؤسسات','organizations.edit':'تعديل المؤسسات والأجهزة',packages:'الباقات والاشتراكات',codes:'أكواد الخصم',offers:'العروض',usage:'الاستهلاك',security:'الأمن',support:'الدعم',ads:'الإعلانات',community:'المجتمع',rewards:'المكافآت',suspend:'إيقاف المؤسسات',admins:'مستخدمو الإدارة',settings:'الإعدادات'};
let ownerKey='',token='',me=null,current='home',currentPage=1,filter='',search='',since='',profileId=null,version=0;
const can=p=>!p||me?.permissions.includes(p), fmt=v=>v===null||v===undefined||v===''?'غير متاح':esc(v), when=v=>{if(!v)return '—';let d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);let z=n=>String(n).padStart(2,'0');return esc(d.getFullYear()+'/'+z(d.getMonth()+1)+'/'+z(d.getDate())+' '+z(d.getHours())+':'+z(d.getMinutes()))};
async function api(path,method='GET',data){let r=await fetch(path.startsWith('/')?path:'/owner/api/v2/'+path,{method,headers:{'Content-Type':'application/json',...(ownerKey?{'X-Owner-Key':ownerKey}:{}),...(token?{'X-Admin-Session':token}:{})},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store'});let d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تنفيذ الطلب');return d}
function flash(t){$('flash').textContent=t;$('flash').hidden=false;setTimeout(()=>$('flash').hidden=true,4500)}
function action(label,fn,cls=''){let b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=async()=>{try{await fn()}catch(e){flash(e.message)}};return b}
function button(label,act,id='',extra=''){return `<button data-act="${act}" data-id="${esc(id)}" ${extra}>${esc(label)}</button>`}
function table(items,columns){return items.length?`<div class="tablewrap"><table><thead><tr>${columns.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${items.map(x=>`<tr>${columns.map(c=>`<td class="${c[2]||''}">${c[1](x)}</td>`).join('')}${current==='community-posts'&&x.user_id?`<td>${button('إعجاب','community-like',x.id)} ${button('مكافأة','community-reward',x.id)}</td>`:''}</tr>`).join('')}</tbody></table></div>`:'<div class="panel empty">لا توجد سجلات في هذا القسم.</div>'}
function pages(d){if(d.total===undefined)return;let b=document.createElement('div');b.className='toolbar';b.append(action('السابق',()=>{currentPage--;render()}),document.createTextNode(`الصفحة ${d.page} · ${d.total} سجل`),action('التالي',()=>{currentPage++;render()}));b.firstChild.disabled=d.page<=1;b.lastChild.disabled=d.page*30>=d.total;$('content').append(b)}
function tabs(options,selected,cb){let wrap=document.createElement('div');wrap.className='tabs';for(let [v,l]of options)wrap.append(action(l,()=>cb(v),selected===v?'primary':''));$('content').append(wrap)}
function note(t){return `<div class="note">${esc(t)}</div>`}
function append(html){$('content').insertAdjacentHTML('beforeend',html)}
function communityPostCards(items){
 if(!items.length)return '<div class="panel empty">لا توجد منشورات في المجتمع.</div>';
 return '<div class="community-feed">'+items.map(x=>`<article class="community-card"><div class="community-card-head">${button(x.name,'community-user',x.user_id)}<span>${when(x.created_at)}</span></div><div class="community-body">${esc(x.body||'')}</div><div class="community-card-actions"><span class="likes">♡ ${Number(x.like_count||0)} إعجاب</span>${button('إعجاب','community-like',x.id)}${button('مكافأة صاحب المنشور','community-reward',x.id)}</div></article>`).join('')+'</div>';
}
function addPlatformAdButton(){
 if(ownerKey){
  $('content').append(action('إضافة إعلان منصة',()=>edit('إضافة إعلان منصة',[f('title','عنوان الإعلان'),f('message','نص الإعلان','textarea'),f('promoCode','كود الخصم (اختياري)'),f('durationDays','مدة العرض بالأيام','number')],{durationDays:30},d=>api('/owner/api/platform-ads','POST',{title:d.title,message:d.message,promoCode:d.promoCode,imageData:'',durationDays:d.durationDays})),'primary'))
 }else $('content').insertAdjacentHTML('beforeend',note('إضافة إعلان المنصة متاحة للمالك فقط.'))
}
const tree=[['الرئيسية','home',null],['الإدارة العامة',null,null,[['الباقات',null,null,[['أسعار الباقات','packages','packages'],['أكواد الخصم','codes','codes'],['عروض الباقات','offers','offers'],['أوائل المشتركين','signup','offers'],['الفروع والإضافات','addons','packages'],['طلبات الاشتراك','subscriptions','packages']]]]],['المؤسسات',null,'organizations.view',[['جميع المؤسسات','organizations','organizations.view'],['حسابات المشتركين','accounts','organizations.view'],['التحقق من الملكية','organization-verifications','organizations.view']]],['الحسابات والاستهلاك',null,'usage',[['الذكاء الاصطناعي','usage-ai','usage'],['واتساب','usage-whatsapp','usage'],['المكالمات','usage-calls','usage']]],['الأمن',null,'security',[['تسجيل الدخول','security-login','security'],['كلمات المرور','security-password','security'],['الأجهزة','security-devices','security'],['التنبيهات','security-alerts','security'],['سجل العمليات','security-audit','security']]],['الدعم',null,'support',[['جديدة','support-open','support'],['جاري العمل عليها','support-in_progress','support'],['محلولة','support-resolved','support'],['مغلقة','support-closed','support']]],['الإعلانات',null,'ads',[['الطلبات','ads-pending','ads'],['المجدولة','ads-scheduled','ads'],['المنشورة','ads-published','ads'],['المنتهية','ads-expired','ads'],['المرفوضة','ads-rejected','ads']]],['شات خدووم',null,'community',[['المنشورات','community-posts','community'],['التعليقات','community-comments','community'],['البلاغات','community-reports','community'],['المستخدمون','community-users','community']]],['مستخدمو الإدارة',null,'admins',[['المستخدمون','admins','admins'],['الأدوار والصلاحيات','roles','admins']]],['الإعدادات','settings','settings']];
tree[7][3].push(['المحادثات المباشرة','community-chat','community']);
tree[7][3].push(['منشورات خدوم','community-admin-posts','community']);
$('communityPost').onclick=()=>edit('منشور خدوم',[f('body','نص المنشور','textarea')],{},d=>api('community/admin-posts','POST',d));
const supportStatus={'support-open':'open','support-in_progress':'in_progress','support-resolved':'resolved','support-closed':'closed'};
const adStatus={'ads-pending':'pending','ads-scheduled':'scheduled','ads-published':'published','ads-expired':'expired','ads-rejected':'rejected'};
function navNode(item){let [label,id,permission,children]=item;if(!can(permission))return null;if(children){let nodes=children.map(navNode).filter(Boolean);if(!nodes.length)return null;let e=document.createElement('details'),s=document.createElement('summary'),sub=document.createElement('div');s.textContent=label;sub.className='sub';sub.append(...nodes);e.append(s,sub);return e}let b=action(label,()=>go(id));b.dataset.route=id;return b}
function go(id){current=id;currentPage=1;filter='';search='';since='';profileId=null;render()}
async function enter(){me=await api('me');$('login').hidden=true;$('app').hidden=false;$('identity').textContent=me.name+' · '+roleNames[me.role];$('nav').replaceChildren(...tree.map(navNode).filter(Boolean));render()}
$('staffLogin').onsubmit=async e=>{e.preventDefault();try{let d=Object.fromEntries(new FormData(e.target));token=(await api('login','POST',d)).token;ownerKey='';e.target.reset();await enter()}catch(e){$('loginError').textContent=e.message}};
$('ownerLogin').onsubmit=async e=>{e.preventDefault();ownerKey=new FormData(e.target).get('key').trim();token='';try{await enter();e.target.reset()}catch(e){ownerKey='';$('loginError').textContent=e.message}};
$('logout').onclick=async()=>{try{await api('logout','POST',{})}finally{ownerKey='';token='';me=null;version++;$('app').hidden=true;$('login').hidden=false;$('content').replaceChildren()}};$('refresh').onclick=()=>render();$('cancel').onclick=()=>$('modal').close();
// Forms use DOM values and escaped labels; no server-supplied HTML is evaluated.
function edit(title,fields,values,save){$('modalTitle').textContent=title;$('formError').hidden=true;$('fields').replaceChildren();for(let f of fields){let [key,label,type,options]=f;let l=document.createElement('label');l.textContent=label;let input=document.createElement(type==='textarea'?'textarea':type==='select'?'select':'input');input.name=key;if(type==='select'){for(let [value,caption]of options){let o=document.createElement('option');o.value=value;o.textContent=caption;input.append(o)}}else if(type!=='textarea')input.type=type||'text';if(type==='checkbox'){l.className='check';input.checked=!!values[key]}else input.value=values[key]??'';if(type==='number'){input.min=0;input.step='any'}l.append(input);$('fields').append(l)}let submit=$('editor').querySelector('[type=submit]');submit.textContent=title==='منشور خدوم'?'إرسال':'حفظ';$('editor').onsubmit=async e=>{e.preventDefault();let d={};for(let [k,,type]of fields){let el=e.target.elements.namedItem(k);d[k]=type==='checkbox'?el.checked:type==='number'?(el.value===''?null:Number(el.value)):el.value}let b=e.submitter;b.disabled=true;try{await save(d);$('modal').close();flash(title==='منشور خدوم'?'تم إرسال المنشور':'تم الحفظ');await render()}catch(e){$('formError').textContent=e.message;$('formError').hidden=false}finally{b.disabled=false}};$('modal').showModal()}
const packageOptions=Object.entries(pkg), f=(key,label,type='text',options)=>[key,label,type,options];
async function render(){let v=++version;let c=$('content');c.innerHTML='<p class="muted">جارٍ تحميل البيانات…</p>';let title=[...$('nav').querySelectorAll('button')].find(b=>b.dataset.route===current)?.textContent||'ملف المؤسسة';$('title').textContent=title;$('breadcrumb').textContent='خدووم / '+title;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===current));
 try{let data;const check=()=>v===version;
 if(window.renderAddons && await renderAddons(current,v))return;
 if(current==='home'){data=await api('summary');if(!check())return;c.innerHTML='<p class="muted">ملخص المنصة · اضغط على البطاقة لعرض التفاصيل. أرقام اليوم حسب UTC.</p><div class="cards" id="cards"></div>';let cards=[['organizations','إجمالي المؤسسات','organizations'],['newToday','المشتركون الجدد اليوم','organizations'],['newMonth','المشتركون الجدد هذا الشهر','organizations'],['ai','استهلاك الذكاء الاصطناعي','usage-ai'],['whatsapp','استهلاك واتساب','usage-whatsapp'],['calls','استهلاك المكالمات','usage-calls'],['ads','الإعلانات النشطة','ads-published'],['support','طلبات الدعم المفتوحة','support-open'],['logins','محاولات الدخول اليوم','security-login'],['passwordResets','إعادة كلمات المرور','security-password'],['alerts','تنبيهات اليوم','security-alerts']];for(let [key,label,target]of cards){if(!(key in data))continue;let b=action('',()=>{go(target);if(key==='newToday'||key==='newMonth'){since=new Date().toISOString().slice(0,key==='newToday'?10:7)+(key==='newMonth'?'-01':'');render()}});b.className='metric'+(key==='support'&&Number(data[key])>0?' alert':'');b.innerHTML=esc(label)+`<strong>${fmt(data[key])}</strong>`;$('cards').append(b)}for(let x of Object.keys(pkg).map(p=>({package:p,total:(data.packages||[]).find(x=>x.package===p)?.total||0})).filter(()=>can('organizations.view'))){let b=action('',()=>{go('organizations');filter=x.package;render()});b.className='metric';b.innerHTML=esc(pkg[x.package])+`<strong>${x.total}</strong>`;$('cards').append(b)}return}
 if(current==='organizations'){data=await api(`organizations?page=${currentPage}&package=${filter}&search=${encodeURIComponent(search)}&since=${since}`);if(!check())return;c.innerHTML='';tabs([['','جميع المؤسسات'],...packageOptions],filter,x=>{filter=x;currentPage=1;render()});let form=document.createElement('form');form.className='toolbar';form.innerHTML=`<input aria-label="بحث المؤسسة" placeholder="اسم المؤسسة أو رقم التواصل" value="${esc(search)}"><button>بحث</button>`;form.onsubmit=e=>{e.preventDefault();search=form.querySelector('input').value;currentPage=1;render()};c.append(form);append(table(data.items,[['المؤسسة',x=>button(x.name,'profile',x.id)],['التواصل',x=>esc(x.phone)],['الباقة',x=>pkg[x.package]],['التسجيل',x=>when(x.created_at)],['بداية الاشتراك',x=>when(x.starts_at)],['النهاية',x=>when(x.expires_at)],['الحالة',x=>x.suspended?'موقوفة':'نشطة'],['آخر نشاط مسجل',x=>when(x.last_login)]]));pages(data);return}
 if(current==='profile'){data=await api('organizations/'+profileId);if(!check())return;c.innerHTML='';$('title').textContent=data.name;append(`<div class="panel"><h3>${esc(data.name)}</h3><p>${esc(data.activity)} · ${esc(data.phone)}</p><p>الباقة: ${pkg[data.package]} · ${data.suspended?'موقوفة':'نشطة'} · التسجيل: ${when(data.created_at)}</p><p>الاشتراك: ${when(data.starts_at)} — ${when(data.expires_at)}</p><div id="orgActions" class="toolbar"></div></div>`);if(data.account_id)$('orgActions').append(action('حساب المشترك والمؤسسات',()=>{addonAccount=data.account_id;current='account-detail';render()}));for(let branch of data.branches||[])$('orgActions').append(action(branch.name,()=>{addonBranch={org:data.id,id:branch.id};current='branch-detail';render()}));if(can('packages'))$('orgActions').append(action('تغيير الباقة',()=>edit('تغيير الباقة',[f('package','الباقة','select',packageOptions),f('durationDays','المدة بالأيام','number')],{package:data.package,durationDays:30},d=>api('/owner/api/organizations/'+profileId+'/package','PUT',d))));if(can('rewards'))$('orgActions').append(action('مكافأة يدوية',()=>edit('مكافأة المؤسسة',[f('kind','نوع المكافأة','select',[['days','إضافة أيام'],['month','شهر مجاني (30 يومًا)'],['vip','VIP لمدة محددة'],['ai','وحدات AI إضافية لليوم']]),f('amount','عدد الأيام أو الوحدات','number'),f('reason','سبب المكافأة','textarea')],{kind:'days',amount:30},d=>api('organizations/'+profileId+'/reward','POST',d))));if(can('suspend'))$('orgActions').append(action(data.suspended?'إعادة التفعيل':'إيقاف المؤسسة',()=>api('organizations/'+profileId+'/status','POST',{suspended:!data.suspended}).then(render),'danger'));if(can('organizations.edit'))$('orgActions').append(action('خروج جميع الأجهزة',()=>api('organizations/'+profileId+'/logout','POST',{}).then(render)));append('<h3>الحسابات والتواصل</h3>'+table(data.users,[['الاسم',x=>esc(x.name)],['البريد',x=>esc(x.email)],['الجوال',x=>esc(x.phone)],['الحالة',x=>x.active?'نشط':'موقوف']]));append('<h3>موظفو AI المستخدمون</h3>'+table(data.employees,[['الموظف',x=>esc(x.employee_type)],['الطلبات',x=>x.requests]]));if(can('usage'))c.append(action('عرض استهلاك المؤسسة',()=>{current='usage-ai';filter='';render()}));append('<h3>الأجهزة النشطة (حتى 100)</h3>'+table(data.devices,[['الجهاز',x=>esc(x.device_name)],['المستخدم',x=>esc(x.name)],['آخر نشاط',x=>when(x.last_seen_at)],['الإجراء',x=>can('organizations.edit')?button('تسجيل خروج','device',x.id):'—']]));append('<h3>الإعلانات (آخر 50)</h3>'+table(data.ads,[['العنوان',x=>esc(x.title)],['نهاية الإعلان',x=>when(x.expires_at)]]));append('<h3>المكافآت اليدوية</h3>'+table(data.rewards,[['النوع',x=>esc(x.kind)],['العدد',x=>x.amount],['السبب',x=>esc(x.reason)],['المسؤول',x=>esc(x.actor)],['التاريخ',x=>when(x.created_at)]]));return}
 if(current==='packages'){data=await api('packages');if(!check())return;c.innerHTML=note('الأسعار وحدود طلبات AI اليومية مرتبطة بالخادم. وحدات المكالمات وواتساب ومزايا الباقة تحتاج أن يدعمها مسار الخدمة قبل تطبيق حدودها.');append(table(data,[['الباقة',x=>pkg[x.package]],['شهري ر.س',x=>x.monthly],['سنوي ر.س',x=>x.yearly],['طلبات AI / يوم',x=>x.ai_daily],['المميزات',x=>esc(x.features),'wrap'],['إدارة',x=>button('تعديل','package',x.package)]]));c._items=data;return}
 if(current==='codes'){data=await api('codes?page='+currentPage);if(!check())return;c._items=data.items;c.innerHTML='';c.append(action('إنشاء كود خصم',()=>edit('كود خصم جديد',[f('code','الكود'),f('recipient_name','صاحب الكود'),f('discount_percent','نسبة الخصم %','number'),f('discount_amount','أو مبلغ الخصم ر.س','number'),f('starts_at','يبدأ في','datetime-local'),f('expires_at','ينتهي في','datetime-local'),f('max_uses','عدد الاستخدامات المسموحة','number'),f('eligible_packages','الباقات','select',[['basic,vip','الأساسية وVIP'],['basic','الأساسية'],['vip','VIP']])],{discount_percent:20,discount_amount:0,max_uses:100,eligible_packages:'basic,vip'},d=>api('codes','POST',d)),'primary'));append(table(data.items,[['الكود',x=>esc(x.code_prefix)],['صاحبه',x=>esc(x.recipient_name)],['الخصم',x=>x.discount_amount?x.discount_amount+' ر.س':x.discount_percent+'%'],['الاستخدام',x=>x.used_count+' / '+x.max_uses],['البداية',x=>when(x.starts_at)],['النهاية',x=>when(x.expires_at)],['إجراء',x=>button('تعديل','code-edit',x.id)+button(x.active?'إيقاف':'تشغيل','code-toggle',x.id,`data-active="${x.active?0:1}"`)]]));pages(data);return}
 if(current==='offers'){data=await api('offers');if(!check())return;c.innerHTML='';c.append(action('عروض الفروع المرتبطة بالباقات',()=>go('addon-offers')));c.append(action('إضافة عرض',()=>edit('عرض باقة',[f('label','اسم العرض'),f('package','الباقات المشمولة','select',[...packageOptions.slice(1),['basic,vip','الأساسية وVIP']]),f('offer_type','نوع العرض','select',[['price','سعر خاص'],['percent','خصم بنسبة'],['bonus','أشهر مجانية إضافية']]),f('discount_percent','نسبة الخصم %','number'),f('paid_months','الأشهر المدفوعة','number'),f('bonus_months','الأشهر المجانية','number'),f('price_sar','إجمالي سعر العرض ر.س','number'),f('starts_at','البداية','datetime-local'),f('ends_at','النهاية','datetime-local')],{package:'basic',offer_type:'price',discount_percent:0,paid_months:1,bonus_months:0,price_sar:49},d=>api('offers','POST',d)),'primary'));append(table(data,[['العرض',x=>esc(x.label)],['الباقة',x=>pkg[x.package]],['الأشهر',x=>x.paid_months+' + '+x.bonus_months],['الإجمالي',x=>x.price_sar],['البداية',x=>when(x.starts_at)],['النهاية',x=>when(x.ends_at)],['الحالة',x=>x.effective_active?'فعال':'متوقف أو خارج المدة'],['إدارة',x=>button(x.active?'إيقاف':'تشغيل','offer-toggle',x.id,`data-active="${x.active?0:1}"`)]]));return}
 if(current==='signup'){data=await api('/owner/api/signup-offer');if(!check())return;c.innerHTML=`<div class="panel"><h3>أوائل المشتركين</h3><p>المستفيدون: ${data.claimed} / ${data.max_claims} · المتبقي: ${data.remaining}</p><p>الباقة: ${pkg[data.package]} · المدة: ${data.months} أشهر</p><p>${data.enabled&&data.remaining>0?'فعال':'متوقف أو اكتملت المقاعد'}</p></div>`;c.append(action('تعديل العرض',()=>edit('أوائل المشتركين',[f('max_claims','عدد المستفيدين','number'),f('package','الباقة','select',packageOptions.slice(1)),f('months','عدد الأشهر','number'),f('enabled','فعال','checkbox')],data,d=>api('/owner/api/signup-offer','PUT',{...d,revision:data.revision}))));return}
 if(current.startsWith('usage-')){let type=current.split('-')[1];data=await api(`usage?type=${type}&package=${filter}&page=${currentPage}${profileId?'&organization='+profileId:''}`);if(!check())return;c.innerHTML='';tabs([['','جميع الباقات'],...packageOptions],filter,x=>{filter=x;currentPage=1;render()});if(data.summary)append(`<div class="panel stats"><span>الكل: ${data.summary.total}</span><span>اليوم: ${data.summary.today}</span><span>الشهر: ${data.summary.month}</span></div>`);append(note(data.note||'')+table(data.items,[['المؤسسة',x=>can('organizations.view')?button(x.name,'profile',x.id):esc(x.name)],['الباقة',x=>pkg[x.package]],['الإجمالي',x=>fmt(x.total)],['استهلاك اليوم / الحد',x=>type==='ai'?`${fmt(x.today)} من ${fmt(x.daily_limit)}`:fmt(x.today)],['الشهر',x=>fmt(x.month)],['المتبقي اليوم',x=>fmt(x.remaining)],['المحادثات',x=>fmt(x.conversations)],['التكلفة',x=>fmt(x.cost)]]));pages(data);return}
 if(current.startsWith('security-')){data=await api('security?type='+current.split('-')[1]+'&page='+currentPage);if(!check())return;c.innerHTML=data.note?note(data.note):'';let columns=current==='security-audit'?[['المسؤول',x=>esc(x.actor)],['الإجراء',x=>esc(x.action)],['الهدف',x=>esc(x.target)],['الوقت',x=>when(x.created_at)]]:current==='security-devices'?[['الجهاز',x=>esc(x.device_name)],['المستخدم',x=>esc(x.name)],['موثوق',x=>x.trusted?'نعم':'لا'],['آخر نشاط',x=>when(x.last_seen_at)]]:[['المؤسسة',x=>esc(x.organization_name)],['الحدث',x=>esc(x.action)],['التفاصيل',x=>esc(x.summary),'wrap'],['الوقت',x=>when(x.created_at)]];append(table(data.items,columns));pages(data);if(data.unknownLogins?.length)append('<h3>محاولات باسم حساب غير متاح</h3>'+table(data.unknownLogins,[['الحساب',x=>esc(x.account)],['الوقت',x=>when(x.created_at)]]));if(data.adminLogins?.length)append('<h3>آخر محاولات دخول الإدارة</h3>'+table(data.adminLogins,[['الحساب',x=>esc(x.account)],['النتيجة',x=>x.success?'ناجحة':'فاشلة'],['الوقت',x=>when(x.created_at)]]));return}
 if(current==='support'||current.startsWith('support-')){let status=supportStatus[current]??filter;data=await api('support?status='+status+'&page='+currentPage);if(!check())return;c.innerHTML='';tabs([['','الكل'],['open','جديدة'],['in_progress','جاري العمل'],['resolved','محلولة'],['closed','مغلقة']],status,x=>{filter=x;currentPage=1;render()});c._items=data.items;append(table(data.items,[['المؤسسة',x=>can('organizations.view')?button(x.organization_name,'profile',x.organization_id):esc(x.organization_name)],['الباقة',x=>pkg[x.package]],['المشكلة',x=>esc(x.message),'wrap'],['الجهاز / الإصدار',x=>fmt(x.device_name)+' / '+fmt(x.app_version)],['الوقت',x=>when(x.created_at)],['الحالة',x=>esc(x.status)],['إدارة',x=>button('فتح الطلب','ticket',x.id)+button('حذف الطلب','ticket-delete',x.id)]]));pages(data);return}
 if(current==='ads'||current.startsWith('ads-')){let status=adStatus[current]??filter;data=await api('ads?status='+status+'&page='+currentPage);if(!check())return;c.innerHTML='';addPlatformAdButton();tabs([['','الكل'],['pending','طلبات جديدة / مراجعة'],['scheduled','مجدولة'],['published','منشورة'],['expired','منتهية'],['rejected','مرفوضة'],['stopped','متوقفة']],status,x=>{filter=x;current='ads';currentPage=1;render()});c._items=data.items;append(table(data.items,[['المؤسسة',x=>esc(x.organization_name)],['الإعلان',x=>(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(x.image_data||'')?`<img class="ad" alt="صورة الإعلان" src="${esc(x.image_data)}"><br>`:'')+esc(x.title)+'<br>'+esc(x.message),'wrap'],['البداية',x=>when(x.scheduled_at||x.approved_at)],['النهاية',x=>when(x.expires_at)],['الحالة',x=>esc(x.status)],['إدارة',x=>button('مراجعة','ad',x.id)+button('حذف','ad-delete',x.id)]]));pages(data);return}
 if(current==='admins'||current==='roles'){data=await api('admins');if(!check())return;c.innerHTML='';c._items=data.items;if(current==='roles'){append(table(Object.entries(data.roles),[['الدور',x=>roleNames[x[0]]],['الصلاحيات',x=>x[1].map(p=>esc(permissionNames[p])).join('، '),'wrap']]));return}c.append(action('إضافة موظف إداري',()=>adminForm({},data),'primary'));append(table(data.items,[['الاسم',x=>esc(x.name)],['اسم المستخدم',x=>esc(x.username)],['الدور',x=>roleNames[x.role]],['الحالة',x=>x.active?'نشط':'موقوف'],['إدارة',x=>button('تعديل','admin',x.id)]]));c._adminData=data;return}
 if(current==='subscriptions'){data=await api('/owner/api/subscription-requests');if(!check())return;c.innerHTML='';c._items=data;append(table(data,[['المؤسسة',x=>esc(x.organization_name)],['الباقة المطلوبة',x=>pkg[x.requested_package]],['الحالة',x=>esc(x.status)],['إجراء',x=>x.status==='pending'?button('مراجعة الاشتراك','subscription',x.id):'—']]));return}
 if(current.startsWith('community-')){let kind=current.slice(10);data=await api('community/'+kind+'?page='+currentPage);if(!check())return;c.innerHTML='';c._items=data.items;if(kind==='posts'){append('<p class="muted">المنشورات مرتبة من الأكثر إعجابًا. اضغط على اسم العضو لعرض حسابه أو على المكافأة لتكريمه.</p>'+communityPostCards(data.items));pages(data);return}append(table(data.items,[['المستخدم',x=>button(x.name,'community-user',kind==='users'?x.id:x.user_id)],['النص / البلاغ',x=>esc(x.body||x.reason||x.organization_name),'wrap'],['الوقت',x=>when(x.created_at||x.last_post)],['الحالة',x=>esc(x.status||(x.hidden?'مخفي':'ظاهر'))],['إجراء',x=>kind==='reports'?button('معالجة البلاغ','community-report',x.id):kind==='users'?'—':button(x.hidden?'إظهار':'إخفاء','community-hide',x.id,`data-kind="${kind}" data-hidden="${x.hidden?0:1}"`)]]));pages(data);return}
 if(current==='settings'){data=await api('settings');if(!check())return;c.innerHTML=`<div class="panel"><p>قاعدة البيانات: ${esc(data.database)}</p><p>مدة جلسة الموظف الإداري: ${data.sessionHours} ساعات</p><p>عدد النتائج في الصفحة: ${data.pageSize}</p></div>`+note(data.note);return}
 }catch(e){if(v===version)c.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function adminForm(x,d){let fields=[f('name','اسم الموظف'),f('username','اسم المستخدم بالإنجليزية'),f('password',x.id?'كلمة مرور جديدة (اتركها للإبقاء)':'كلمة المرور — 12 حرفًا على الأقل','password'),f('role','الدور الجاهز','select',Object.entries(roleNames)),f('active','نشط','checkbox'),...d.permissions.map(p=>f('perm_'+p,permissionNames[p],'checkbox'))];let permissions=x.permissions?JSON.parse(x.permissions):d.roles.support;let values={role:'support',active:true,...x,...Object.fromEntries(d.permissions.map(p=>['perm_'+p,permissions.includes(p)]))};edit(x.id?'تعديل موظف إداري':'موظف إداري جديد',fields,values,v=>{let permissions=d.permissions.filter(p=>v['perm_'+p]);return api('admins'+(x.id?'/'+x.id:''),x.id?'PUT':'POST',{name:v.name,username:v.username,password:v.password,role:v.role,active:v.active,permissions})});$('editor').elements.role.onchange=e=>{for(let p of d.permissions)$('editor').elements.namedItem('perm_'+p).checked=d.roles[e.target.value].includes(p)}}
$('content').onclick=async e=>{let b=e.target.closest('[data-act]');if(!b)return;let id=b.dataset.id,act=b.dataset.act,items=$('content')._items||[];let x=items.find(x=>String(x.id)===id);try{
 if(act==='profile'){profileId=Number(id);current='profile';currentPage=1;await render()}
 if(act==='device'){await api('organizations/'+profileId+'/logout','POST',{device:id});await render()}
 if(act==='package'){x=items.find(x=>x.package===id);edit('إعدادات '+pkg[id],[f('monthly','شهري ر.س','number'),f('yearly','سنوي ر.س','number'),f('ai_daily','طلبات AI في اليوم','number'),f('ai_employees','موظفو AI — تعريف الباقة','number'),f('whatsapp_units','وحدات واتساب — تعريف الباقة','number'),f('calls_units','دقائق المكالمات — تعريف الباقة','number'),f('ads_units','الإعلانات — تعريف الباقة','number'),f('features','المميزات','textarea')],x,d=>api('packages','PUT',{...d,package:id}))}
 if(act==='code-edit')edit('تعديل الكود مع حفظ عدد استخداماته',[f('recipient_name','صاحب الكود'),f('discount_percent','النسبة %','number'),f('discount_amount','أو مبلغ الخصم','number'),f('max_uses','الاستخدامات المسموحة','number'),f('eligible_packages','الباقات','select',[['basic,vip','الأساسية وVIP'],['basic','الأساسية'],['vip','VIP']]),f('starts_at','البداية','datetime-local'),f('expires_at','النهاية','datetime-local')],{...x,starts_at:x.starts_at?.slice(0,16),expires_at:x.expires_at?.slice(0,16)},d=>api('codes/'+id,'PUT',d));
 if(act==='code-toggle'||act==='offer-toggle'){await api((act==='code-toggle'?'codes/':'offers/')+id,'PUT',{active:b.dataset.active==='1'});render()}
 if(act==='ticket'){edit('طلب الدعم #'+id,[f('status','الحالة','select',[['open','جديدة'],['in_progress','جاري العمل'],['resolved','محلولة'],['closed','مغلقة']]),f('owner_reply','الرد للمشترك','textarea'),f('note','ملاحظة داخلية جديدة','textarea')],x,d=>api('support/'+id,'PUT',d));if(x.organization_id)$('fields').append(action('فتح ملف المؤسسة والإجراءات',()=>{$('modal').close();profileId=Number(x.organization_id);current='profile';render()}));if(x.notes.length){let p=document.createElement('p');p.className='muted';p.textContent=x.notes.map(n=>n.actor+': '+n.note).join('\n');$('fields').append(p)}}
 if(act==='ticket-delete'){if(confirm('حذف طلب الدعم نهائيًا؟')){await api('support/'+id,'DELETE');render()}}
 if(act==='ad-delete'){if(confirm('حذف الإعلان من العرض؟ سيبقى سجل الإجراء محفوظًا.')){await api('ads/'+id,'DELETE');render()}}
 if(act==='ad')edit('مراجعة الإعلان',[f('status','الحالة','select',[['pending','تحت المراجعة'],['published','موافقة ونشر'],['scheduled','جدولة'],['rejected','رفض'],['stopped','إيقاف']]),f('scheduled_at','موعد البداية','datetime-local'),f('expires_at','موعد النهاية','datetime-local'),f('review_note','ملاحظة المراجعة','textarea')],{...x,scheduled_at:x.scheduled_at?.slice(0,16),expires_at:x.expires_at?.slice(0,16)},d=>api('ads/'+id,'PUT',d));
 if(act==='community-like'){await api('community/likes/'+id,'POST',{});flash('تم تسجيل الإعجاب');render()}
 if(act==='community-reward')edit('مكافأة صاحب المنشور',[f('kind','نوع المكافأة','select',[['days','أيام إضافية'],['ai','رصيد AI إضافي']]),f('amount','العدد','number'),f('reason','السبب','textarea')],{kind:'days',amount:30,reason:'منشور مميز في مجتمع خدوم'},d=>api('community/rewards/'+id,'POST',d));
 if(act==='community-hide'){await api('community/'+b.dataset.kind+'/'+id,'PUT',{hidden:b.dataset.hidden==='1'});render()}
 if(act==='community-report')edit('معالجة البلاغ',[f('status','الحالة','select',[['open','مفتوح'],['closed','مغلق']]),f('note','ملاحظة الإدارة','textarea')],x,d=>api('community/reports/'+id,'PUT',d));
 if(act==='community-user'&&current==='community-chat'){let chat=await api('community/chat/'+id),text=(chat.items||[]).map(m=>(m.sender==='admin'?'الإدارة':'العضو')+': '+m.body).join('\n\n');edit('محادثة مباشرة مع '+(x?.name||'العضو'),[f('body','اكتب ردك','textarea')],{},d=>api('community/chat/'+id,'POST',d));let log=document.createElement('pre');log.textContent=text||'لا توجد رسائل بعد';log.style.whiteSpace='pre-wrap';log.style.maxHeight='260px';log.style.overflow='auto';$('fields').prepend(log)}
 if(act==='community-user'){let user=await api('community/users/'+id);edit(user.name,[f('organization','المؤسسة'),f('phone','الجوال'),f('email','البريد')],{organization:user.organization_name,phone:user.phone,email:user.email},async()=>{});let submit=$('editor').querySelector('[type=submit]');submit.hidden=true;$('modal').addEventListener('close',()=>submit.hidden=false,{once:true});if(can('rewards'))$('fields').append(action('إعطاء مكافأة يدوية',()=>{ $('modal').close();edit('مكافأة '+user.name,[f('kind','النوع','select',[['days','أيام مجانية'],['vip','VIP'],['ai','وحدات AI لليوم']]),f('amount','العدد','number'),f('reason','السبب','textarea')],{amount:30,kind:'days'},d=>api('organizations/'+user.organization_id+'/reward','POST',d))}));}
 if(act==='admin')adminForm(x,$('content')._adminData);
 if(act==='subscription')edit('مراجعة الاشتراك',[f('status','القرار','select',[['approved','موافقة'],['rejected','رفض']]),f('package','الباقة','select',packageOptions),f('durationDays','مدة الأيام','number')],{status:'approved',package:x.requested_package,durationDays:30},d=>api('/owner/api/subscription-requests/'+id,'PUT',{action:d.status==='approved'?'approve':'reject',selectedPackage:d.package,durationDays:d.durationDays}));
}catch(e){flash(e.message)}};
